// Copie de country_to_flag_dict (backend) : clé = nom du pays en minuscules
const COUNTRY_TO_FLAG: Record<string, string> = {
  "abkhazie": "🏳️",
  "afghanistan": "🇦🇫",
  "afrique du sud": "🇿🇦",
  "albanie": "🇦🇱",
  "algérie": "🇩🇿",
  "allemagne": "🇩🇪",
  "andorre": "🇦🇩",
  "angola": "🇦🇴",
  "antigua et barbuda": "🇦🇬",
  "arabie saoudite": "🇸🇦",
  "argentine": "🇦🇷",
  "arménie": "🇦🇲",
  "australie": "🇦🇺",
  "autriche": "🇦🇹",
  "azerbaïdjan": "🇦🇿",
  "bahamas": "🇧🇸",
  "bahreïn": "🇧🇭",
  "bangladesh": "🇧🇩",
  "barbade": "🇧🇧",
  "belgique": "🇧🇪",
  "belize": "🇧🇿",
  "bénin": "🇧🇯",
  "bhoutan": "🇧🇹",
  "biélorussie": "🇧🇾",
  "birmanie": "🇲🇲",
  "bolivie": "🇧🇴",
  "bosnie herzégovine": "🇧🇦",
  "botswana": "🇧🇼",
  "brésil": "🇧🇷",
  "brunei": "🇧🇳",
  "bulgarie": "🇧🇬",
  "burkina faso": "🇧🇫",
  "burundi": "🇧🇮",
  "cambodge": "🇰🇭",
  "cameroun": "🇨🇲",
  "canada": "🇨🇦",
  "cap vert": "🇨🇻",
  "république centrafricaine": "🇨🇫",
  "chili": "🇨🇱",
  "chine": "🇨🇳",
  "chypre": "🇨🇾",
  "chypre du nord": "🏳️",
  "colombie": "🇨🇴",
  "comores": "🇰🇲",
  "république du congo": "🇨🇬",
  "république démocratique du congo": "🇨🇩",
  "îles cook": "🇨🇰",
  "corée du nord": "🇰🇵",
  "corée du sud": "🇰🇷",
  "costa rica": "🇨🇷",
  "côte d'ivoire": "🇨🇮",
  "croatie": "🇭🇷",
  "cuba": "🇨🇺",
  "danemark": "🇩🇰",
  "djibouti": "🇩🇯",
  "république dominicaine": "🇩🇴",
  "dominique": "🇩🇲",
  "égypte": "🇪🇬",
  "émirats arabes unis": "🇦🇪",
  "équateur": "🇪🇨",
  "érythrée": "🇪🇷",
  "espagne": "🇪🇸",
  "estonie": "🇪🇪",
  "eswatini": "🇸🇿",
  "états unis": "🇺🇸",
  "éthiopie": "🇪🇹",
  "fidji": "🇫🇯",
  "finlande": "🇫🇮",
  "france": "🇫🇷",
  "gabon": "🇬🇦",
  "gambie": "🇬🇲",
  "géorgie": "🇬🇪",
  "ghana": "🇬🇭",
  "grèce": "🇬🇷",
  "grenade": "🇬🇩",
  "guatemala": "🇬🇹",
  "guinée": "🇬🇳",
  "guinée bissau": "🇬🇼",
  "guinée équatoriale": "🇬🇶",
  "guyana": "🇬🇾",
  "haïti": "🇭🇹",
  "honduras": "🇭🇳",
  "hongrie": "🇭🇺",
  "inde": "🇮🇳",
  "indonésie": "🇮🇩",
  "irak": "🇮🇶",
  "iran": "🇮🇷",
  "irlande": "🇮🇪",
  "islande": "🇮🇸",
  "israël": "🇮🇱",
  "italie": "🇮🇹",
  "jamaïque": "🇯🇲",
  "japon": "🇯🇵",
  "jordanie": "🇯🇴",
  "kazakhstan": "🇰🇿",
  "kenya": "🇰🇪",
  "kirghizistan": "🇰🇬",
  "kiribati": "🇰🇮",
  "kosovo": "🇽🇰",
  "koweït": "🇰🇼",
  "laos": "🇱🇦",
  "lesotho": "🇱🇸",
  "lettonie": "🇱🇻",
  "liban": "🇱🇧",
  "liberia": "🇱🇷",
  "libye": "🇱🇾",
  "liechtenstein": "🇱🇮",
  "lituanie": "🇱🇹",
  "luxembourg": "🇱🇺",
  "macédoine du nord": "🇲🇰",
  "madagascar": "🇲🇬",
  "malaisie": "🇲🇾",
  "malawi": "🇲🇼",
  "maldives": "🇲🇻",
  "mali": "🇲🇱",
  "malte": "🇲🇹",
  "maroc": "🇲🇦",
  "îles marshall": "🇲🇭",
  "maurice": "🇲🇺",
  "mauritanie": "🇲🇷",
  "mexique": "🇲🇽",
  "micronésie": "🇫🇲",
  "moldavie": "🇲🇩",
  "monaco": "🇲🇨",
  "mongolie": "🇲🇳",
  "monténégro": "🇲🇪",
  "mozambique": "🇲🇿",
  "namibie": "🇳🇦",
  "nauru": "🇳🇷",
  "népal": "🇳🇵",
  "nicaragua": "🇳🇮",
  "niger": "🇳🇪",
  "nigeria": "🇳🇬",
  "niue": "🇳🇺",
  "norvège": "🇳🇴",
  "nouvelle zélande": "🇳🇿",
  "oman": "🇴🇲",
  "ossétie du sud alanie": "🏳️",
  "ouganda": "🇺🇬",
  "ouzbékistan": "🇺🇿",
  "pakistan": "🇵🇰",
  "palaos": "🇵🇼",
  "palestine": "🇵🇸",
  "panama": "🇵🇦",
  "papouasie nouvelle guinée": "🇵🇬",
  "paraguay": "🇵🇾",
  "pays bas": "🇳🇱",
  "pérou": "🇵🇪",
  "philippines": "🇵🇭",
  "pologne": "🇵🇱",
  "portugal": "🇵🇹",
  "qatar": "🇶🇦",
  "roumanie": "🇷🇴",
  "royaume uni": "🇬🇧",
  "russie": "🇷🇺",
  "rwanda": "🇷🇼",
  "sénégal": "🇸🇳",
  "serbie": "🇷🇸",
  "singapour": "🇸🇬",
  "slovaquie": "🇸🇰",
  "slovénie": "🇸🇮",
  "somalie": "🇸🇴",
  "soudan": "🇸🇩",
  "soudan du sud": "🇸🇸",
  "suède": "🇸🇪",
  "suisse": "🇨🇭",
  "syrie": "🇸🇾",
  "taïwan": "🇹🇼",
  "tanzanie": "🇹🇿",
  "tchad": "🇹🇩",
  "république tchèque": "🇨🇿",
  "thaïlande": "🇹🇭",
  "turquie": "🇹🇷",
  "ukraine": "🇺🇦",
  "uruguay": "🇺🇾",
  "vietnam": "🇻🇳",
  "zambie": "🇿🇲",
  "zimbabwe": "🇿🇼",
  "salvador": "🇸🇻",
  "saint christophe et niévès": "🇰🇳",
  "saint marin": "🇸🇲",
  "saint vincent et les grenadines": "🇻🇨",
  "sainte lucie": "🇱🇨",
  "salomon": "🇸🇧",
  "samoa": "🇼🇸",
  "sao tomé et principe": "🇸🇹",
  "seychelles": "🇸🇨",
  "sierra leone": "🇸🇱",
  "somaliland": "🏳️",
  "sri lanka": "🇱🇰",
  "suriname": "🇸🇷",
  "tadjikistan": "🇹🇯",
  "timor oriental": "🇹🇱",
  "togo": "🇹🇬",
  "tonga": "🇹🇴",
  "trinité et tobago": "🇹🇹",
  "tunisie": "🇹🇳",
  "turkménistan": "🇹🇲",
  "tuvalu": "🇹🇻",
  "vanuatu": "🇻🇺",
  "vatican": "🇻🇦",
  "venezuela": "🇻🇪",
  "yémen": "🇾🇪",
}

// Noms de la liste de pays écrits différemment dans le dictionnaire
const ALIASES: Record<string, string> = {
  "viêt nam": "vietnam",
  "îles salomon": "salomon",
  "são tomé et principe": "sao tomé et principe",
}

export function country_to_flag(country: string): string {
  const key = country.trim().toLowerCase()
  return COUNTRY_TO_FLAG[ALIASES[key] ?? key] ?? ""
}
