# Generated by Django 6.1 on 2026-08-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WikipediaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=300, unique=True)),
                ('page_url', models.URLField(max_length=500)),
                ('picture_url', models.URLField(blank=True, max_length=500, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name_standard', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name_standard', models.CharField(blank=True, max_length=100, null=True)),
                ('job', models.CharField(blank=True, max_length=300, null=True)),
                ('town_birth_place', models.CharField(blank=True, max_length=300, null=True)),
                ('town_birth_place_href', models.CharField(blank=True, max_length=500, null=True)),
                ('birth_town_localisation', models.CharField(blank=True, max_length=300, null=True)),
                ('country_birth_place', models.CharField(blank=True, max_length=200, null=True)),
                ('time_period_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('continent_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('region_of_birth', models.CharField(blank=True, max_length=200, null=True)),
                ('birth_date', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_year', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_month', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_day', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_month_day', models.CharField(blank=True, max_length=100, null=True)),
                ('town_death_place', models.CharField(blank=True, max_length=300, null=True)),
                ('town_death_place_href', models.CharField(blank=True, max_length=500, null=True)),
                ('town_death_localisation', models.CharField(blank=True, max_length=300, null=True)),
                ('country_death_place', models.CharField(blank=True, max_length=200, null=True)),
                ('continent_of_death', models.CharField(blank=True, max_length=100, null=True)),
                ('region_of_death', models.CharField(blank=True, max_length=200, null=True)),
                ('death_date', models.CharField(blank=True, max_length=100, null=True)),
                ('death_year', models.CharField(blank=True, max_length=100, null=True)),
                ('death_month', models.CharField(blank=True, max_length=100, null=True)),
                ('death_day', models.CharField(blank=True, max_length=100, null=True)),
                ('death_month_day', models.CharField(blank=True, max_length=100, null=True)),
                ('born_and_died_in_the_same_town', models.CharField(default='False', max_length=20)),
                ('born_and_died_in_the_same_country', models.CharField(default='False', max_length=20)),
                ('born_and_died_in_the_same_continent', models.CharField(default='False', max_length=20)),
                ('born_and_died_in_the_same_region', models.CharField(default='False', max_length=20)),
                ('born_before_christ', models.CharField(default='False', max_length=20)),
                ('died_before_christ', models.CharField(default='False', max_length=20)),
                ('born_and_died_before_christ', models.CharField(default='False', max_length=20)),
                ('born_and_died_after_christ', models.CharField(default='False', max_length=20)),
                ('born_before_christ_and_died_after_christ', models.CharField(default='False', max_length=20)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('is_alive', models.BooleanField(default=True)),
                ('gender', models.CharField(blank=True, max_length=30, null=True)),
                ('power_ranking', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('position_percentage', models.FloatField(blank=True, null=True)),
                ('grade_over_20', models.FloatField(blank=True, null=True)),
                ('first_char_of_the_page', models.CharField(blank=True, max_length=1, null=True)),
                ('wikipedia_page_lenght', models.IntegerField(default=0)),
                ('all_links_of_a_page', models.JSONField(blank=True, default=list)),
                ('number_of_links', models.IntegerField(default=0)),
                ('preciseness_level', models.IntegerField(blank=True, null=True)),
                ('list_of_unpreciseness_data', models.JSONField(blank=True, default=list)),
                ('country_birth_place_emoji', models.CharField(blank=True, max_length=20, null=True)),
                ('country_death_place_emoji', models.CharField(blank=True, max_length=20, null=True)),
                ('is_updated', models.BooleanField(default=False)),
                ('number_of_update', models.IntegerField(default=0)),
            ],
        ),
    ]
