# Generated by Django 5.2.7 on 2026-10-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipediauser',
            name='picture_url',
            field=models.URLField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='wikipediauseruniquetown',
            name='picture_url',
            field=models.URLField(blank=True, max_length=2500, null=True),
        ),
    ]
