# Generated by Django 5.2.7 on 2026-10-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_wikipediauser_picture_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipediauser',
            name='data_to_update',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
