# Generated by Django 5.2.7 on 2026-10-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_wikipediauser_data_to_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiopediaUserToUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=300, unique=True)),
                ('data_to_update', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name='wikipediauser',
            name='data_to_update',
        ),
    ]
