# Generated by Django 5.2.7 on 2026-10-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_wikiopediausertoupdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiopediausertoupdate',
            name='update_level',
            field=models.IntegerField(default=1),
        ),
    ]
