# Generated by Django 5.2.7 on 2026-10-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_wikiopediausertoupdate_update_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiopediausertoupdate',
            name='nb_of_bad_report',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wikiopediausertoupdate',
            name='nb_of_good_report',
            field=models.IntegerField(default=0),
        ),
    ]
