# Generated by Django 5.2.7 on 2026-10-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_wikiopediausertoupdate_nb_of_bad_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipediauser',
            name='list_of_game_user_can_play',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
