# Generated by Django 5.2.7 on 2026-10-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_wikipediauser_list_of_game_user_can_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipediauser',
            name='nb_of_translation',
            field=models.IntegerField(default=0),
        ),
    ]
