"""A file that contain all global variable"""

MONTH_TO_NUMBER_DICT: dict[str, str] = {
    "janvier": "01",
    "fevrier": "02",
    "février": "02",
    "mars": "03",
    "avril": "04",
    "mai": "05",
    "juin": "06",
    "juillet": "07",
    "aout": "08",
    "août": "08",
    "septembre": "09",
    "octobre": "10",
    "novembre": "11",
    "decembre": "12",
    "décembre": "12"
}

NUMBER_TO_MONTH_DICT: dict[str, str] = {
    "01": "janvier",
    "02": "février",
    "03": "mars",
    "04": "avril",
    "05": "mai",
    "06": "juin",
    "07": "juillet",
    "08": "août",
    "09": "septembre",
    "10": "octobre",
    "11": "novembre",
    "12": "décembre",
}

LIST_OF_MONTH: list[str] = [
    "janvier",
    "février",
    "mars",
    "avril",
    "mai",
    "juin",
    "juillet",
    "août",
    "septembre",
    "octobre",
    "novembre",
    "décembre",
]

ABSOLUTE_DATE_VALUE: int = 1000000

AFRICA: list[str] = [
    "africa du sud",
    "algérie",
    "angola",
    "bénin",
    "botswana",
    "burkina faso",
    "burundi",
    "cameroun",
    "cap-vert",
    "république centrafricaine",
    "comores",
    "république du congo",
    "république démocratique du congo",
    "côte d'ivoire",
    "djibouti",
    "égypte",
    "érythrée",
    "eswatini",
    "éthiopie",
    "gabon",
    "gambie",
    "ghana",
    "guinée",
    "guinée-bissau",
    "guinée équatoriale",
    "kenya",
    "lesotho",
    "liberia",
    "libye",
    "madagascar",
    "malawi",
    "mali",
    "maroc",
    "maurice",
    "mauritanie",
    "mozambique",
    "namibie",
    "niger",
    "nigeria",
    "ouganda",
    "rwanda",
    "são tomé-et-principe",
    "sénégal",
    "seychelles",
    "sierra leone",
    "somalie",
    "soudan",
    "soudan du sud",
    "tanzanie",
    "tchad",
    "togo",
    "tunisie",
    "zambie",
    "zimbabwe"
]

AMERICA: list[str] = [
    "antigua-et-barbuda",
    "argentine",
    "bahamas",
    "barbade",
    "belize",
    "bolivie",
    "brésil",
    "canada",
    "chili",
    "colombie",
    "costa rica",
    "cuba",
    "république dominicaine",
    "dominique",
    "équateur",
    "états-unis",
    "grenade",
    "guatemala",
    "guyana",
    "haïti",
    "honduras",
    "jamaïque",
    "mexique",
    "nicaragua",
    "panama",
    "paraguay",
    "pérou",
    "saint-christophe-et-niévès",
    "saint-vincent-et-les grenadines",
    "sainte-lucie",
    "salvador",
    "suriname",
    "trinité-et-tobago",
    "uruguay",
    "venezuela"
]

ASIA: list[str] = [
    "abkhazie",
    "afghanistan",
    "arabie saoudite",
    "arménie",
    "azerbaïdjan",
    "bahreïn",
    "bangladesh",
    "bhoutan",
    "birmanie",
    "brunei",
    "cambodge",
    "chine",
    "chypre",
    "chypre du nord",
    "corée du nord",
    "corée du sud",
    "émirats arabes unis",
    "géorgie",
    "inde",
    "indonésie",
    "irak",
    "iran",
    "israël",
    "japon",
    "jordanie",
    "kazakhstan",
    "kirghizistan",
    "koweït",
    "laos",
    "liban",
    "malaisie",
    "maldives",
    "mongolie",
    "népal",
    "oman",
    "ossétie du sud-alanie",
    "ouzbékistan",
    "pakistan",
    "palestine",
    "philippines",
    "qatar",
    "russie",
    "singapour",
    "sri lanka",
    "syrie",
    "tadjikistan",
    "taïwan",
    "thaïlande",
    "timor oriental",
    "turkménistan",
    "turquie",
    "viêt nam",
    "yémen"
]

EUROPE: list[str] = [
    "albanie",
    "allemagne",
    "andorre",
    "angleterre",
    "autriche",
    "belgique",
    "biélorussie",
    "bosnie-herzégovine",
    "bulgarie",
    "croatie",
    "danemark",
    "écosse",
    "espagne",
    "estonie",
    "finlande",
    "france",
    "grèce",
    "hongrie",
    "irlande",
    "irlande du nord",
    "islande",
    "italie",
    "kosovo",
    "lettonie",
    "liechtenstein",
    "lituanie",
    "luxembourg",
    "macédoine",
    "macédoine du nord",
    "malte",
    "moldavie",
    "monaco",
    "monténégro",
    "norvège",
    "pays-bas",
    "pays de galles",
    "pologne",
    "portugal",
    "roumanie",
    "royaume-uni",
    "saint-marin",
    "serbie",
    "slovaquie",
    "slovénie",
    "suède",
    "suisse",
    "république tchèque",
    "ukraine",
    "vatican"
]

OCEANIA: list[str] = [
    "australie",
    "fidji",
    "îles cook",
    "kiribati",
    "îles marshall",
    "micronésie",
    "nauru",
    "niue",
    "nouvelle-zélande",
    "palaos",
    "papouasie-nouvelle-guinée",
    "îles salomon",
    "samoa",
    "tonga",
    "tuvalu",
    "vanuatu"
]

LIST_OF_REGIONS_NAME = [
    "Europe du Nord",
    "Europe de l'Ouest",
    "Europe du Sud",
    "Europe de l'Est",
    "Afrique du Nord",
    "Afrique de l'Ouest",
    "Afrique centrale",
    "Afrique de l'Est",
    "Afrique australe",
    "Moyen-Orient",
    "Asie centrale",
    "Asie de l'Est",
    "Asie du Sud",
    "Asie du Sud-Est",
    "Caucase",
    "Amérique anglo-saxonne",
    "Amérique centrale",
    "Caraïbes",
    "Amérique du Sud",
    "Australasie",
    "Mélanésie",
    "Micronésie",
    "Polynésie",
]
LIST_OF_CONTINENTS: list[str] = [AFRICA,AMERICA,ASIA,EUROPE,OCEANIA]

JOBS: list[str] = [
    "Écrivain",
    "Auteur",
    "Romancier",
    "Poète",
    "Essayiste",
    "Musicien",
    "Journaliste",
    "Réalisateur",
    "Producteur de cinéma",
    "Scénariste",
    "Acteur",
    "Actrice",
    "Chanteur",
    "Chanteuse",
    "Musicien",
    "Compositeur",
    "Parolier",
    "Producteur musical",
    "Artiste",
    "Peintre",
    "Sculpteur",
    "Photographe",
    "Architecte",
    "Designer",
    "Illustrateur",
    "Dessinateur",
    "Humoriste",
    "Comédien",
    "Présentateur de télévision",
    "Animateur de radio",
    "Animateur de télévision",
    "Mannequin",
    "Danseur",
    "Chorégraphe",
    "Acteur de théâtre",
    "Metteur en scène",
    "Dramaturge",
    "Historien",
    "Philosophe",
    "Sociologue",
    "Anthropologue",
    "Linguiste",
    "Chercheur",
    "Scientifique",
    "Physicien",
    "Chimiste",
    "Mathématicien",
    "Biologiste",
    "Médecin",
    "Psychiatre",
    "Inventeur",
    "Ingénieur",
    "Informaticien",
    "Développeur",
    "Entrepreneur",
    "Homme d'affaires",
    "Femme d'affaires",
    "Industriel",
    "Banquier",
    "Économiste",
    "Juriste",
    "Avocat",
    "Magistrat",
    "Diplomate",
    "Militaire",
    "Officier",
    "Explorateur",
    "Aventurier",
    "Athlète",
    "Footballeur",
    "Basketteur",
    "Tennisman",
    "Pilote automobile",
    "Pilote d'avion",
    "Sportif",
    "Entraîneur sportif",
    "Joueur d'échecs",
    "Chef cuisinier",
    "Cuisinier",
    "Architecte paysagiste",
    "Religieux",
    "Théologien",
    "Prêtre",
    "Moine",
    "Activiste",
    "Militant",
    "Homme politique",
    "Femme politique",
    "Député",
    "Président",
    "Premier ministre",
    "Roi",
    "Reine",
    "Prince",
    "Professeur",
    "Enseignant",
    "Universitaire",
    "Critique littéraire",
    "Critique d'art",
    "Éditeur",
    "Souverain",
    "Prêtre catholique",
    "Claveciniste",
    "Auteur de jeux de société",
    "Prêtre orthodoxe",
    "Ayatollah",
    "Conteur",
    "Pianiste",
    "Personnalité politique",
    "Infirmier",
    "Saxophoniste",
    "Cadi",
    "Personnalité du monde des affaires",
    "Pilote (aviation)",
    "Charpentier",
    "Rabbin",
    "Artiste peintre",
    "Ingénieur civil",
    "Lama (bouddhisme)",
    "Astronome",
    "Maître spirituel",
    "Botaniste",
    "Violoncelliste",
    "Maréchal",
    "Commissaire aux comptes",
    "Groupie",
    "Artiste lyrique",
    "Défenseur des droits de l'homme",
    "Arbitre (football)",
    "Haute fonction publique",
    "Potier (métier)",
    "Vizir",
    "Auteur-compositeur",
    "Syndicaliste",
    "Guitariste",
    "Évêque catholique",
    "Troubadour",
    "Mangaka",
    "Psychologue",
    "Altiste",
    "Illusionniste",
    "Instituteur",
    "Avocat (métier)",
    "Pasteur (christianisme)",
    "Producteur de télévision",
    "Directeur de la photographie",
    "Financier",
    "Urgentiste",
    "Barde (poète gael)",
    "Graphiste",
    "Disc jockey",
    "Chef d'orchestre",
    "Maître écrivain",
    "Consultant",
    "Caricaturiste",
    "Peintre de cour",
    "Corsaire",
    "Styliste",
    "Harpiste",
    "Metteur en scène",
    "Créateur de caractères",
    "Sculpteur",
    "Influenceur web",
    "Marchand d'art",
    "Vitrailliste",
    "Administrateur colonial",
    "Homme d'État",
    "Attachée de presse",
    "Policier",
    "Entomologiste",
    "Marchand (commerce)",
    "Mannequin",
    "Musicien électronique",
    "Plasticien",
    "Sage-femme",
    "Artiste contemporain",
    "Capitaine de navire",
    "Réalisateur de télévision",
    "Chroniqueur (littéraire)",
    "Abbesse",
    "Violoniste",
    "Publiciste",
    "Sexologue",
    "Trompettiste",
    "Ingénieur du son",
    "Critique de cinéma",
    "Patineur artistique",
    "Artiste plasticienne",
    "Acteur de doublage",
    "Cascadeur",
    "Journaliste sportif",
    "Torero",
    "Fleuriste",
    "Archiviste",
    "Bassiste",
    "Chercheur universitaire",
    "Restaurateur d'art",
    "Dessinateur humoristique",
    "Librettiste",
    "Directeur général",
    "Dialoguiste",
    "Cryptographe",
    "Musicologue",
    "Parasitologue",
    "Anthropologue",
    "Reporter",
    "Conquistador",
    "Producteur de radio",
    "Paysagiste",
    "Chirurgien",
    "Agriculteur",
    "Heilpraktiker",
    "Vigneron",
    "Pilote (profession maritime)",
    "Directeur de casting",
    "Modiste",
    "Naturaliste",
    "Cow-boy",
    "Sommelier",
    "Monteur son",
    "Luthier",
    "Éleveur équin",
    "Historien",
    "Historien de la philosophie",
    "Humoriste",
    "Pharmacien",
    "Pâtissier",
    "Parfumeur",
    "Jardinier",
    "Guide de haute montagne",
    "Narrateur",
    "Horloger",
    "Navigateur (marine)",
    "Architecte naval",
    "Seigneur de guerre",
    "Juge",
    "Conservateur de musée",
    "Conservateur du patrimoine",
    "Relieur",
    "Photographe",
    "Orfèvre",
    "Notaire",
    "Entrepreneur",
    "Directeur des ressources humaines",
    "Commissaire d'exposition",
    "Bassoniste",
    "Tromboniste",
    "Tailleur de pierre",
    "Viticulteur",
    "Écuyer",
    "Libraire",
    "Fonctionnaire impérial",
    "Zoologiste",
    "Photographe plasticien",
    "Agent de renseignement",
    "Maquilleur",
    "Conducteur de train",
    "Vacher",
    "Instrumentiste",
    "Ingénieur logiciel",
    "Radioamateur",
    "Espion",
    "Maître à danser",
    "Facteur d'orgues",
    "Affichiste",
    "Éditeur (métier)",
    "Armateur",
    "Corniste",
    "Sénéchal",
    "Microbiologiste",
    "Facteur de pianos",
    "Barrister",
    "Reporter-photographe",
    "Statisticien",
    "Monteur",
    "Coiffeur",
    "Skipper",
    "Professeur documentaliste",
    "Sommelier",
    "Coiffeur",
    "Professeur (enseignant)",
    "Investisseur",
    "Docteur en médecine",
    "Vidéaste web",
    "Artiste de rue",
    "Géographe",
    "Tueur à gages",
    "Intelligence artificielle (chercheur)",
    "Busshi",
    "Chaman",
    "Boulanger",
    "Écrivain voyageur",
    "Dessinateur de bande dessinée",
    "Scénariste de bande dessinée",
    "Président-directeur général",
    "Scribe",
    "Youtubeur virtuel",
    "Directeur littéraire",
    "Producteur de cinéma",
    "Chef militaire",
    "Illustrateur botanique",
    "Lexicographe",
    "Fondeur de cloches",
    "Productrice de cinéma",
    "Directeur artistique",
    "Correspondant local de presse",
    "Tatoueur",
    "Modèle (art)",
    "Pathologiste",
    "Écrivain public",
    "Critique de vin",
    "Promoteur immobilier",
    "Dirigeant",
    "Sommelier",
    "Lissier",
    "Professeur documentaliste",
    "Chocolatier",
    "Horloger",
    "Architecte",
    "Marin (profession)",
    "Assistant réalisateur",
    "Typographe",
    "Écrivaine",
    "Reporter",
    "Conquistador",
    "Griot",
    "Photographe de mode",
    "Monteur",
    "Dramaturge",
    "Professeur",
    "Superviseur des effets visuels",
    "Producteur de jeux vidéo",
    "Maquilleur",
    "Paysagiste",
    "Chocolatier",
    "Tailleur de pierre",
    "Chef de chœur",
    "Correspondant de guerre",
    "Chef opérateur",
    "Directeur de théâtre",
    "Marin",
    "Skipper",
    "Viticulteur",
    "Conseiller d'État",
    "Trésorier",
    "Agent de change",
    "Forgeron",
    "Art numérique (artiste)",
    "Fondeur",
    "Ingénieur militaire",
    "Ingénieur agronome",
    "Urbaniste",
    "Spin doctor",
    "Chef de produit",
    "Trésorier (comptabilité)",
    "Directeur",
    "Chef d'entreprise",
    "Restaurateur",
    "Banquier d'affaires",
    "Conservateur du patrimoine",
    "Relieur",
    "Pharmacien",
    "Marchand mercier",
    "Jardinier",
    "Capitaine",
    "Docteur",
    "Scientifique",
    "Programmeur",
    "Développeur",
    "Ingénieur",
    "Autrice",
    "Romancière",
    "Poétesse",
    "Essayiste",  # épicène
    "Musicienne",
    "Journaliste",  # épicène
    "Réalisatrice",
    "Productrice musicale",
    "Compositrice",
    "Parolière",
    "Peintre",  # épicène
    "Sculptrice",
    "Photographe",  # épicène
    "Architecte",  # épicène
    "Designeuse",
    "Illustratrice",
    "Dessinatrice",
    "Humoriste",  # épicène
    "Comédienne",
    "Présentatrice de télévision",
    "Animatrice de radio",
    "Animatrice de télévision",
    "Danseuse",
    "Chorégraphe",  # épicène
    "Actrice de théâtre",
    "Metteuse en scène",
    "Historienne",
    "Philosophe",  # épicène
    "Sociologue",  # épicène
    "Anthropologue",  # épicène
    "Linguiste",  # épicène
    "Chercheuse",
    "Scientifique",  # épicène
    "Physicienne",
    "Chimiste",
    "Mathématicienne",
    "Biologiste",
    "Médecin",  # épicène
    "Psychiatre",  # épicène
    "Inventrice",
    "Ingénieure",
    "Informaticienne",
    "Développeuse",
    "Entrepreneuse",
    "Industrielle",
    "Banquière",
    "Économiste",  # épicène
    "Juriste",  # épicène
    "Avocate",
    "Magistrate",
    "Diplomate",  # épicène
    "Militaire",  # épicène
    "Officière",
    "Exploratrice",
    "Aventurière",
    "Athlète",  # épicène
    "Footballeuse",
    "Basketteuse",
    "Joueuse de tennis",
    "Pilote automobile",  # épicène
    "Pilote d'avion",  # épicène
    "Sportive",
    "Entraîneuse sportive",
    "Joueuse d'échecs",
    "Cheffe cuisinière",
    "Cuisinière",
    "Religieuse",
    "Théologienne",
    "Prêtresse",
    "Moniale",
    "Activiste",  # épicène
    "Militante",
    "Députée",
    "Présidente",
    "Première ministre",
    "Princesse",
    "Professeure",
    "Enseignante",
    "Universitaire",  # épicène
    "Critique littéraire",  # épicène
    "Critique d'art",  # épicène
    "Éditrice",
    "Souveraine",
    "Claveciniste",  # épicène
    "Autrice de jeux de société",
    "Conteuse",
    "Pianiste",  # épicène
    "Personnalité politique",  # épicène
    "Infirmière",
    "Saxophoniste",  # épicène
    "Cadie",
    "Charpentière",
    "Rabbine",
    "Astronome",  # épicène
    "Botaniste",  # épicène
    "Violoncelliste",  # épicène
    "Commissaire aux comptes",  # épicène
    "Artiste lyrique",  # épicène
    "Défenseuse des droits de l'homme",
    "Arbitre",
    "Potière",
    "Autrice-compositrice",
    "Syndicaliste",  # épicène
    "Guitariste",  # épicène
    "Mangaka",  # épicène
    "Psychologue",  # épicène
    "Altiste",  # épicène
    "Illusionniste",  # épicène
    "Institutrice",
    "Productrice de télévision",
    "Directrice de la photographie",
    "Financière",
    "Urgentiste",  # épicène
    "Graphiste",  # épicène
    "Disc-jockey",
    "Cheffe d'orchestre",
    "Consultante",
    "Caricaturiste",  # épicène
    "Peintre de cour",  # épicène
    "Corsaire",  # épicène
    "Créatrice de caractères",
    "Influenceuse web",
    "Marchande d'art",
    "Vitrailliste",  # épicène
    "Administratrice coloniale",
    "Policière",
    "Entomologiste",  # épicène
    "Marchande",
    "Musicienne électronique",
    "Plasticienne",
    "Capitaine de navire",  # épicène
    "Réalisatrice de télévision",
    "Chroniqueuse",
    "Publicitaire",
    "Sexologue",  # épicène
    "Trompettiste",  # épicène
    "Ingénieure du son",
    "Critique de cinéma",  # épicène
    "Patineuse artistique",
    "Actrice de doublage",
    "Cascadeuse",
    "Journaliste sportive",
    "Fleuriste",  # épicène
    "Archiviste",  # épicène
    "Bassiste",  # épicène
    "Chercheuse universitaire",
    "Restauratrice d'art",
    "Dessinatrice humoristique",
    "Librettiste",  # épicène
    "Directrice générale",
    "Dialoguiste",  # épicène
    "Cryptographe",  # épicène
    "Musicologue",  # épicène
    "Parasitologue",  # épicène
    "Reporteuse",
    "Chirurgienne",
    "Agricultrice",
    "Vigneronne",
    "Directrice de casting",
    "Naturaliste",  # épicène
    "Cow-girl",
    "Sommelière",
    "Monteuse son",
    "Luthière",
    "Éleveuse équine",
    "Pharmacienne",
    "Pâtissière",
    "Parfumeuse",
    "Jardinière",
    "Guide de haute montagne",  # épicène
    "Narratrice",
    "Horlogère",
    "Navigatrice",
    "Juge",  # épicène
    "Conservatrice de musée",
    "Conservatrice du patrimoine",
    "Relieuse",
    "Orfèvre",  # Orfévesse est très rare
    "Notaire",  # épicène
    "Directrice des ressources humaines",
    "Commissaire d'exposition",  # épicène
    "Bassoniste",  # épicène
    "Tromboniste",  # épicène
    "Tailleuse de pierre",
    "Viticultrice",
    "Écuyère",
    "Libraire",  # épicène
    "Zoologiste",  # épicène
    "Photographe plasticienne",
    "Agente de renseignement",
    "Maquilleuse",
    "Conductrice de train",
    "Vachère",
    "Instrumentiste",  # épicène
    "Ingénieure logiciel",
    "Espionne",
    "Affichiste",  # épicène
    "Éditrice",
    "Armatrice",
    "Corniste",  # épicène
    "Microbiologiste",  # épicène
    "Factrice de pianos",
    "Statisticienne",
    "Monteuse",
    "Coiffeuse",
    "Skipeuse",
    "Professeure documentaliste",
    "Investisseuse",
    "Docteure en médecine",
    "Vidéaste web",  # épicène
    "Boulangère",
    "Écrivaine voyageuse",
    "Dessinatrice de bande dessinée",
    "Scénariste de bande dessinée",  # épicène
    "Présidente-directrice générale",
    "Scribe",  # épicène
    "Youtubeuse virtuelle",
    "Directrice littéraire",
    "Cheffe militaire",
    "Illustratrice botanique",
    "Lexicographe",  # épicène
    "Directrice artistique",
    "Correspondante locale de presse",
    "Tatoueuse",
    "Pathologiste",  # épicène
    "Écrivaine publique",
    "Critique de vin",  # épicène
    "Promotrice immobilière",
    "Dirigeante",
    "Lissière",
    "Assistante réalisatrice",
    "Typographe",  # épicène
    "Griotte",
    "Photographe de mode",  # épicène
    "Superviseuse des effets visuels",
    "Productrice de jeux vidéo",
    "Cheffe de chœur",
    "Correspondante de guerre",
    "Cheffe opératrice",
    "Directrice de théâtre",
    "Marinière",
    "Conseillère d'État",
    "Trésorière",
    "Agente de change",
    "Forgeronne",
    "Fondeuse",
    "Ingénieure militaire",
    "Ingénieure agronome",
    "Urbaniste",  # épicène
    "Cheffe de produit",
    "Trésorière (comptabilité)",
    "Directrice",
    "Cheffe d'entreprise",
    "Restauratrice",
    "Banquière d'affaires",
    "Programmeuse"
]

CITIES: list[str] = [
    "Houston",
    "Marseille",
    "Alger",
    "Ouagadougou",
    "Dakar",
    "Bamberg",
    "Vérone",
    "Orléans",
    "Abidjan",
    "Bongouanou",
    "Meilen",
    "Potsdam",
    "Yaté",
    "Hollerich",
    "Ribeauvillé",
    "Bogota",
    "Rome",
    "Paris",
    "Rosières",
    "Montréal",
    "Chicoutimi",
    "Roura",
    "Aoste",
    "Munich",
    "Lille",
    "Namur",
    "Meknès",
    "Tanger",
    "Tizi Ouzou",
    "Tan-Tan",
    "Nzérékoré",
    "Philadelphie",
    "Vesoul",
    "Nîmes",
    "Bourg-en-Bresse",
    "Lannion",
    "Saïgon",
    "Douala",
    "Nanterre",
    "Schaerbeek",
    "Tivoli",
    "Hambourg",
    "Männedorf",
    "Bordeaux",
    "Garnsee",
    "Reims",
    "Meißen",
    "Zurich",
    "Coppet",
    "Bône",
    "Salmaise",
    "Genève",
    "Budapest",
    "Francfort-sur-le-Main",
    "Wurtzbourg",
    "Eichstätt",
    "Näples",
    "Barranquilla",
    "Königsberg",
    "Berlin",
    "Berlin-Spandau",
    "Aberdeen",
    "Lausanne",
    "Drummondville",
    "Annemasse",
    "Moscou",
    "Saint-Pierre-en-Val",
    "Port-au-Prince",
    "Vincennes",
    "Colmar",
    "Chartres",
    "Anduze",
    "Weimar",
    "Sydney",
    "Nazareth",
    "Zanzibar",
    "Shanghai",
    "Charquemont",
    "Fatick",
    "Meyrin",
    "Aix-en-Provence",
    "Kaunas",
    "Montemor-o-Novo",
    "Ploudalmézeau",
    "Amiens",
    "Néfiach",
    "Saint-Jean",
    "Linguère",
    "Bolton",
    "Louga",
    "Naplouse",
    "Zacatecas",
    "Stendal",
    "Saint-Pierre-de-Sorel",
    "Libreville",
    "Bignona",
    "Tournai",
    "Santos",
    "Avallon",
    "Aarhus",
    "Bologne",
    "Belluno",
    "Santiago",
    "Venise",
    "Amberg",
    "Aalen",
    "Lviv",
    "Chełm Śląski",
    "Gourdinne",
    "Rivesaltes",
    "Victoriaville",
    "Marnes-la-Coquette",
    "Tchortkiv",
    "Saint-Julien-en-Born",
    "Wamba",
    "Fréjus",
    "Commercy",
    "Yzeure",
    "Lunel",
    "Maastricht",
    "Rhyl",
    "Chicago",
    "Greifswald",
    "Calvi",
    "Crémone",
    "Londres",
    "Frederiksberg",
    "Asciano",
    "Dubăsari",
    "Saint-Mihiel",
    "Denain",
    "Lyon",
    "Saint-Avold",
    "Puylaurens",
    "Poperinge",
    "Helsinki",
    "Cambrai",
    "Lübeck",
    "Mantes-la-Ville",
    "Holwierde",
    "Saint-Étienne",
    "Boma",
    "Boston",
    "Kiel",
    "Strasbourg",
    "Bruxelles",
    "Charleroi",
    "Lunéville",
    "Vienne",
    "Salzbourg",
    "Copenhague",
    "Salon-de-Provence",
    "Milan",
    "Campobasso",
    "Montevideo",
    "Messine",
    "Antananarivo",
    "Cyrène",
    "Angers",
    "Saint-Nicolas-d'Aliermont",
    "Durango",
    "Perpignan",
    "Nevers",
    "Vichy",
    "Dresde",
    "Brünn",
    "Prague",
    "Beyrouth",
    "Kyoustendil",
    "Téhéran",
    "Culhuacan",
    "Wetzlar",
    "Stargard",
    "Champsecret",
    "Neuchâtel",
    "Quimper",
    "Nyon",
    "Ensival",
    "Besançon",
    "Darmstadt",
    "Vilvorde",
    "Rotterdam",
    "Conques",
    "Orange",
    "Las Palmas de Gran Canaria",
    "Ankara",
    "Marsan",
    "Istanbul",
    "Bambey",
    "Épinay-sur-Seine",
    "Caracas",
    "Kinshasa",
    "Goma",
    "Bellinzone",
    "Porto-Novo",
    "Ostende",
    "Szamocin",
    "Morges",
    "Yamoussoukro",
    "Dunmurry",
    "Tacoma",
    "Pontevedra",
    "Galați",
    "Dunkerque",
    "Metz",
    "Kilkenny",
    "Tunis",
    "Toulouse",
    "Comè",
    "Biarritz",
    "Chantilly",
    "Wavre",
    "Saint-Paul-en-Jarez",
    "Firminy",
    "Macenta",
    "Orgerus",
    "Hof-sur-Saale",
    "Stralsund",
    "Vence",
    "Lorient",
    "Newark",
    "Yankton",
    "Linz",
    "Varsovie",
    "Bălți",
    "Saint",
    "Lecce",
    "Fredericton",
    "Dubrovnik",
    "Zagreb",
    "Winnipeg",
    "Mazamet",
    "Toronto",
    "Sieradz",
    "Livourne",
    "Boulogne-Billancourt",
    "Tallinn",
    "Oslo",
    "Springfield",
    "Essex",
    "Gassin",
    "Stockton-on-Tees",
    "Tournan-en-Brie",
    "Lassy",
    "Voujeaucourt",
    "Givors",
    "Maui",
    "Rheine",
    "Brême",
    "Trostberg",
    "Gransee",
    "Barcelone",
    "Florence",
    "Catanzaro",
    "Bissen",
    "Albacete",
    "Neuilly-sur-Seine",
    "Mexico",
    "Cles",
    "Gand",
    "Nice",
    "Ixelles",
    "Auffay",
    "Purmerland",
    "Douarnenez",
    "Uccle",
    "Frasnes-lez-Buissenal",
    "Sedan",
    "Iași",
    "Saint-Louis",
    "Brazzaville",
    "Saint-Nicolas",
    "Colombes",
    "Krefeld",
    "Leuze-en-Hainaut",
    "Rodez",
    "Carhaix-Plouguer",
    "Bronx",
    "Alost",
    "Épinal",
    "Hanoï",
    "Saint-Raymond",
    "Genlis",
    "Bondy",
    "Dole",
    "Burzaco",
    "Cúcuta",
    "Aubervilliers",
    "Bienne",
    "Brissago",
    "Antigonish",
    "Dortmund",
    "Lignol",
    "London",
    "Bucarest",
    "Burgos",
    "Sarreguemines",
    "Amsterdam",
    "Détroit",
    "Delémont",
    "Belfort",
    "Whitehorse",
    "Skopje",
    "Saint-Yrieix-la-Perche",
    "Gatineau",
    "Medellín",
    "Mont-Joli",
    "Kaolack",
    "Souleimaniye",
    "Boise",
    "Trois-Pistoles",
    "Hollywood",
    "Avranches",
    "Kangu",
    "Vinchio",
    "Il-Furjana",
    "Gijón",
    "Benghazi",
    "Saint-Denis",
    "Muralto",
    "Stuttgart",
    "Mayence",
    "Bocaiúva",
    "Addis-Abeba",
    "Cologne",
    "Villemoisson-sur-Orge",
    "Blois",
    "Reus",
    "Chișinău",
    "Kielce",
    "Richmond",
    "Bougouni",
    "Casablanca",
    "Fès",
    "Zhengzhou",
    "Bombay",
    "Sacramento",
    "Wiesbaden",
    "Pointe-à-Pitre",
    "Bamenda",
    "Vevey",
    "Berne",
    "Geseke",
    "Rio de Janeiro",
    "Halifax",
    "Dublin",
    "Elora",
    "Saint-Pétersbourg",
    "Lipcani",
    "Gênes",
    "Turin",
    "Gołdap",
    "Clervaux",
    "Bridgend",
    "Guéret",
    "Rougé",
    "Curitiba",
    "Pont-en-Royans",
    "LaSalle",
    "Leeds",
    "Remscheid",
    "Zwickau",
    "Brno",
    "Ramnäs",
    "Yaoundé",
    "Nancy",
    "Villarzel",
    "Frouard",
    "Lisbonne",
    "Leipzig",
    "Snowidza",
    "Schlieben",
    "Cassel",
    "Kleinobringen",
    "Vendenheim",
    "Anvers",
    "Nevele",
    "Casalmaggiore",
    "Crissier",
    "Malansac",
    "Laval",
    "Mbujimayi",
    "Carcassonne",
    "Alençon",
    "Rouen",
    "Ludwigshafen",
    "Béziers",
    "Fortaleza",
    "Gävle",
    "Grenoble",
    "Ladimirevci",
    "Gaziantep",
    "Tshikapa",
    "Parme",
    "Písek",
    "Craon",
    "Bytów",
    "Wessin",
    "Magdebourg",
    "Aplahoué",
    "Cholet",
    "Arleuf",
    "Garessio",
    "Ternitz",
    "Presbourg",
    "Évry-Courcouronnes",
    "Velika Kladuša",
    "Molfetta",
    "Butembo",
    "Dijon",
    "Sarrebourg",
    "São Paulo",
    "Cagnes-sur-Mer",
    "La Haye",
    "Crotone",
    "Charlesbourg",
    "Cognac",
    "León",
    "Zamora",
    "Valladolid",
    "Ivano-Frankivsk",
    "Limoges",
    "Lazise",
    "Brooklyn",
    "Dorsten",
    "Aix-la-Chapelle",
    "Achern",
    "Vallorbe",
    "Asmara",
    "Mirande",
    "Rennes",
    "Sète",
    "Brest",
    "Cap-Chat",
    "Luc-la-Primaube",
    "Douai",
    "Cuarny",
    "Ébreuil",
    "Clarmont",
    "Cracovie",
    "Olmütz",
    "Brugg",
    "Graz",
    "Hanovre",
    "Mannheim",
    "Wiltz",
    "Bobo-Dioulasso",
    "Villecresnes",
    "Brive-la-Gaillarde",
    "Pontedeume",
    "Bourg-Saint-Andéol",
    "Dambach-la-Ville",
    "Haine-Saint-Paul",
    "Lessines",
    "Oakland",
    "Pérouse",
    "Goilberdingen",
    "Vergt",
    "Bora-Bora",
    "Coire",
    "Baltimore",
    "Pasadena",
    "Indianapolis",
    "Kroppenstedt",
    "Abbeville",
    "Recife",
    "Erfurt",
    "Tianjin",
    "Amélie-les-Bains",
    "Cincinnati",
    "Lugano",
    "Merano",
    "Agde",
    "Athènes",
    "Brescia",
    "Corridonia",
    "Imola",
    "Gubbio",
    "Kyoto",
    "Jodhpur",
    "Bruges",
    "Vicence",
    "Roubaix",
    "Mascouche",
    "Stockholm",
    "Cossonay",
    "Fontainebleau",
    "Thoune",
    "Rimouski",
    "Trois-Rivières",
    "Sainte-Marie",
    "Val-d'Or",
    "Lagnieu",
    "Ennery",
    "Melun",
    "Suresnes",
    "Yogyakarta",
    "Taza",
    "Wörgl",
    "Carthage",
    "Bonn",
    "Raeren",
    "Versmold",
    "Malmö",
    "Bâle",
    "Appenzell",
    "Geisenheim",
    "Dallas",
    "Pula",
    "Sprottau",
    "Oranienbourg",
    "Glaris",
    "Kremsmünster",
    "Berlin-Siemensstadt",
    "Chester",
    "Neu-Ulm",
    "Bünde",
    "Longuefuye",
    "Luxeuil-les-Bains",
    "Valjouffrey",
    "Datteln",
    "Narbonne",
    "Bonchamp-lès-Laval",
    "Saint-André-les-Alpes",
    "Grimma",
    "Mauron",
    "Massachusetts",
    "Mauterndorf",
    "Wels",
    "Gnoien",
    "Kukës",
    "Limbourg-sur-la-Lahn",
    "Brwice",
    "Drożyna",
    "Strépy-Bracquegnies",
    "Thiers",
    "Tochigi",
    "Île des Pins",
    "Romans-sur-Isère",
    "Rusutsu",
    "Séoul",
    "Imintanoute",
    "Atlanta",
    "Pékin",
    "Longwy",
    "Bachhagel",
    "Akureyri",
    "Stettin",
    "Bielefeld",
    "Bissau",
    "Gdańsk",
    "Fanjeaux",
    "Arras",
    "Matanzas",
    "Omsk",
    "Yokohama",
    "Novohrad-Volynskyï",
    "Banja Luka",
    "Raubach",
    "Berlin-Schöneberg",
    "Tchernivtsi",
    "Passau",
    "Parakou",
    "Montpellier",
    "Maubeuge",
    "Kalocsa",
    "Reggio de Calabre",
    "Dnipropetrovsk",
    "Yverdon-les-Bains",
    "Cambrils",
    "Montargis",
    "Estagel",
    "Carmaux",
    "Chusclan",
    "Lutry",
    "Granville",
    "Cannes",
    "Saint-Maur-des-Fossés",
    "Aurillac",
    "Saint-Marcellin",
    "Hasparren",
    "Kapurthala",
    "Guayaquil",
    "Sofia",
    "Madrid",
    "Glasgow",
    "Hanna",
    "Saskatoon",
    "Rimini",
    "Palenque",
    "Soleure",
    "Saint-Jérôme",
    "Louny",
    "Cap de Trafalgar",
    "Loubressac",
    "Bonoua",
    "Sartène",
    "Porto-Vecchio",
    "Nantes",
    "Briançon",
    "Loos-en-Gohelle",
    "Civray",
    "Verdun",
    "Mulhouse",
    "Tirlemont",
    "Bapaume",
    "Sud-Kivu",
    "Niort",
    "Galéria",
    "Aignan",
    "Saint-Gilles",
    "Vernon",
    "Souchez",
    "Guengat",
    "Saint-Lô",
    "Warmeriville",
    "Valenciennes",
    "Louviers",
    "Kedgwick",
    "Quaregnon",
    "Fontoy",
    "Flacey-en-Bresse",
    "Périgueux",
    "Angoulême",
    "Poitiers",
    "Forbach",
    "Krattigen",
    "Beaune",
    "Frampton",
    "Berles-au-Bois",
    "Champniers-et-Reilhac",
    "Tours",
    "Bourges",
    "Astaffort",
    "Sainte-Eulalie-en-Born",
    "Rabat",
    "Nouméa",
    "Lapeyrouse",
    "Saint-Isidore",
    "Beauzac",
    "Saint-Sardos",
    "Coarraze",
    "Montivilliers",
    "Vittel",
    "Bastia",
    "Laon",
    "Pistoia",
    "Maisons-Laffitte",
    "Deshaies",
    "Riom",
    "Freetown",
    "Vejle",
    "Incheon",
    "Lima",
    "Eindhoven",
    "Pisco",
    "Dundee",
    "New York",
    "Liverpool",
    "Saint-Jean-sur-Richelieu",
    "Syracuse",
    "Berlin-Charlottenbourg",
    "Wilmington",
    "Saint Catharines",
    "Canterbury",
    "Alderley Edge",
    "Dukinfield",
    "Perwez",
    "Manizales",
    "Witten",
    "Forges-sur-Meuse",
    "Welschenrohr",
    "Berthier-sur-Mer",
    "Bukavu",
    "Neuville-sous-Montreuil",
    "Manhattan",
    "Bayonne",
    "Carnac",
    "Etterbeek",
    "Queens",
    "Beaumont",
    "Melbourne",
    "Offenbach-sur-le-Main",
    "Groix",
    "Bristol",
    "Marbella",
    "Itumbiara",
    "Séville",
    "Alicante",
    "Asuncion",
    "Lokeren",
    "Maceió",
    "Hautmont",
    "Bilbao",
    "Lérida",
    "Pereira",
    "Liège",
    "Saverne",
    "Allouagne",
    "Marvejols",
    "Clermont-Ferrand",
    "Chênée",
    "Rouyn",
    "Nauen",
    "Berlin-Wedding",
    "Klagenfurt",
    "Teplice",
    "Darłowo",
    "Kołobrzeg",
    "Jepara",
    "Gitega",
    "Bunnik",
    "Kashiwa",
    "Montana",
    "Beaconsfield",
    "Shizuoka",
    "Pétion-Ville",
    "Brockton",
    "Cobourg",
    "Sderot",
    "Wendake",
    "Wriezen",
    "Calcutta",
    "Manacor",
    "Cesena",
    "Korhogo",
    "Aalborg",
    "Udine",
    "Caen",
    "Kikwit",
    "Clamart",
    "Saint-Nazaire",
    "Cervia",
    "Raqqa",
    "Yuncheng",
    "Hořovice",
    "Alphen-sur-le-Rhin",
    "Valkenswaard",
    "Sheffield",
    "Tassin-la-Demi-Lune",
    "Narvik",
    "Québec",
    "Karlsruhe",
    "Sukabumi",
    "Valence",
    "Heilly",
    "Suze-la-Rousse",
    "Orbe",
    "La Brévine",
    "Alban",
    "Binche",
    "Rouyn-Noranda",
    "Pointe-Noire",
    "Pernes-les-Fontaines",
    "Nonville",
    "Quéven",
    "Molenbeek-Saint-Jean",
    "Senlis",
    "Frameries",
    "Vire",
    "Louvain",
    "Papeete",
    "Bois-d'Haine",
    "Saint-Amand-les-Eaux",
    "Québec",
    "Uppsala",
    "Lynden",
    "Roverbella",
    "Constantine",
    "Vaison-la-Romaine",
    "Mayenne",
    "Ratisbonne",
    "Weinberg",
    "Tübingen",
    "Pittsburgh",
    "Baie-Saint-Paul",
    "Saint-Imier",
    "Saint-Martin-de-Seignanx",
    "Piré-sur-Seiche",
    "Saumur",
    "Thessalonique",
    "Cheyres",
    "Iriba",
    "Ljubljana",
    "Corbeil-Essonnes",
    "Sulzbach-Rosenberg",
    "Sangerhausen",
    "Asnières-sur-Seine",
    "São João da Madeira",
    "Terrebonne",
    "Vierzon",
    "Arlon",
    "Jumet",
    "Pontcey",
    "Murici",
    "Valens",
    "Wieruszów",
    "Inowrocław",
    "Canelones",
    "Buenos Aires",
    "Estamira",
    "Telfes im Stubai",
    "Pont-l'Abbé",
    "Andorre-la-Vieille",
    "Sanok",
    "Göteborg",
    "Meung-sur-Loire",
    "Sherbrooke",
    "Allonville",
    "Fribourg-en-Brisgau",
    "Montluçon",
    "Londerzeel",
    "Healdsburg",
    "Jakarta",
    "Saint-Quentin",
    "Sainte-Anne-de-la-Pocatière",
    "Langolen",
    "Sant'Angelo Lodigiano",
    "Bénévent",
    "Sinaloa",
    "Cosenza",
    "Düren",
    "Vintimille",
    "Souvret",
    "Ouidah",
    "Rybany",
    "Milton",
    "Flobecq",
    "Birmingham",
    "Berlin-Est",
    "Liesek",
    "Withypool",
    "Padoue",
    "Ferrare",
    "Versailles",
    "Mazy",
    "Oucques",
    "Mostaganem",
    "Sienne",
    "Talence",
    "Calgary",
    "Toulon",
    "Chepetivka",
    "Héraklion",
    "Coinches",
    "Estaires",
    "Oujda",
    "Chabanais",
    "Hirson",
    "Avenches",
    "Béguey",
    "Roanne",
    "Genk",
    "Pančevo",
    "Bratislava",
    "Moyeuvre-Grande",
    "Munakata",
    "Hachiōji",
    "Laghouat",
    "Bizerte",
    "Gouda",
    "Baden-Baden",
    "Bergen",
    "Tiaret",
    "Ourossogui",
    "Chêne-Bougeries",
    "Verviers",
    "El Ksiba",
    "Beuvry",
    "Anápolis",
    "Riec-sur-Bélon",
    "Harrisburg",
    "Little Rock",
    "Mississauga",
    "San Salvador",
    "Dassa-Zoumè",
    "Mons",
    "Allemagne-en-Provence",
    "Niedernai",
    "Soissons",
    "Hilversum",
    "Viazma",
    "Yopougon",
    "Bangkok",
    "Opole",
    "Thunder Bay",
    "Phnom-Penh",
    "Lifou",
    "Hartola",
    "Constantinople",
    "Kharkiv",
    "Iéna",
    "Berlaimont",
    "Saint-Julien-en-Genevois",
    "Woluwe-Saint-Lambert",
    "Saint-Jean-de-Luz",
    "Ouahigouya",
    "Milev",
    "Offenbourg",
    "Bandung",
    "Catane",
    "Coblence",
    "Riga",
    "Rufisque",
    "Nantucket",
    "Ludhiana",
    "Bad Kösen",
    "Chiavenna",
    "Vendôme",
    "Loudima",
    "Ninove",
    "Louiseville",
    "Chihuahua",
    "Saint-Joseph",
    "Mantes-la-Jolie",
    "Camphin-en-Carembault",
    "Anglès",
    "Avignon",
    "Montmerle-sur-Saône",
    "Biedermannsdorf",
    "Cottbus",
    "Hachy",
    "Bohicon",
    "Asbestos",
    "Mossoul",
    "Amstetten",
    "Ivanovo",
    "Anorí",
    "Saragosse",
    "Vänersborg",
    "Wellington",
    "Portsmouth",
    "Tenterden",
    "Altenbourg",
    "Rumilly",
    "Bourg-la-Reine",
    "Loches-sur-Ource",
    "Grigny",
    "Zwolle",
    "Palerme",
    "Vipiteno",
    "Colorno",
    "Cahors",
    "Bouchemaine",
    "Guingamp",
    "Champigny-sur-Marne",
    "Queyrac",
    "Noale",
    "Joigny",
    "Hódmezővásárhely",
    "Torrelavega",
    "Wettingen",
    "Malgaches",
    "Gelsenkirchen",
    "Farmville",
    "Cuxac-Cabardès",
    "Joué-lès-Tours",
    "Fort-de-France",
    "Santiago du Chili",
    "Saint-Gall",
    "Quedlinburg",
    "Oelsnitz",
    "Innsbruck",
    "Fauquemont-sur-Gueule",
    "Ebolowa",
    "Castres",
    "Albi",
    "Marcinelle",
    "Beauvais",
    "Chambéry",
    "Aalter",
    "Ajaccio",
    "Iowa",
    "Ath",
    "Schwendi",
    "Saint-Drézéry",
    "Buffalo",
    "Tirana",
    "Milwaukee",
    "Gagnoa",
    "Ostrava",
    "Moudon",
    "Tacaná",
    "Martigny",
    "Bex",
    "Provins",
    "Saint-Jorioz",
    "Nuremberg",
    "Sotchi",
    "Tarragone",
    "Porto",
    "Réghaïa",
    "Labé",
    "Foumban",
    "Bougainville",
    "Praia",
    "Ushuaïa",
    "Kengtung",
    "Cleveland",
    "Salquenen",
    "Aveiro",
    "Puttaparthi",
    "Višegrad",
    "Koszalin",
    "Xalapa",
    "Hopa",
    "Pristina",
    "Saitama",
    "Kankan",
    "Dielsdorf",
    "Kehra",
    "Diegem",
    "Bratsigovo",
    "Duffel",
    "Tbilissi",
    "Port-Gentil",
    "Kikinda",
    "Zehdenick",
    "Talkeetna",
    "Trondheim",
    "Mechhed",
    "Vanves",
    "Kiev",
    "Lisieux",
    "Asti",
    "Elbląg",
    "Rzeszów",
    "Abéché",
    "Vancouver",
    "Hobart",
    "Agadir",
    "Les Cayes",
    "Cowansville",
    "Virton",
    "Linköping",
    "Seclin",
    "Marconne",
    "Hemmingstedt",
    "Odense",
    "Stratford",
    "Rowley",
    "Greystones",
    "Roskilde",
    "Logroño",
    "Beaugency",
    "Randers",
    "Tokyo",
    "Oulan-Bator",
    "Salerne",
    "Lucerne",
    "Oaxaca",
    "Wattwil",
    "Kaysersberg",
    "La Possession",
    "Rawalpindi",
    "Khartsyzk",
    "Zgierz",
    "Esch-sur-Alzette",
    "Kragujevac",
    "Aire-sur-l'Adour",
    "Granges-près-Marnand",
    "Oneglia",
    "Brie-Comte-Robert",
    "Tchibanga",
    "Schleusingen",
    "Oldenbourg",
    "Seligenstadt",
    "Karachi",
    "Shantou",
    "Jacareí",
    "Barth",
    "Duisbourg",
    "Głogów",
    "Neufelden",
    "Youngstown",
    "Höxter",
    "Bressanone",
    "Osterwieck",
    "Hulan",
    "Silvan",
    "Calakmul",
    "Saint-Martin-de-Ré",
    "Saint-Chamond",
    "Chenu",
    "Perros-Guirec",
    "Pont-à-Mousson",
    "Dinant",
    "Monceau-sur-Sambre",
    "Moûtiers",
    "N'Djaména",
    "Hama",
    "Kandi",
    "Pécs",
    "Pforzheim",
    "Ferrol",
    "Bourbon-Lancy",
    "Monteux",
    "Saint-Laurent-de-la-Salanque",
    "Mirecourt",
    "Auberchicourt",
    "Bafia",
    "Boulogne-sur-Mer",
    "Lambézellec",
    "Differdange",
    "Saint-Affrique",
    "Amagne",
    "Suippes",
    "Litomyšl"
]

NORTHERN_EUROPE = [
    "Angleterre",
    "Danemark",
    "Estonie",
    "Écosse",
    "Finlande",
    "Irlande",
    "Irlande du Nord",
    "Islande",
    "Irlande",
    "Lettonie",
    "Lituanie",
    "Norvège",
    "Pays de Galles",
    "Royaume-Uni",
    "Suède",
]

WESTERN_EUROPE = [
    "Allemagne",
    "Andorre",
    "Autriche",
    "Belgique",
    "France",
    "Liechtenstein",
    "Luxembourg",
    "Monaco",
    "Pays-Bas",
    "Suisse",
]

SOUTHERN_EUROPE = [
    "Albanie",
    "Bosnie-Herzégovine",
    "Chypre",
    "Chypre du Nord",
    "Croatie",
    "Espagne",
    "Grèce",
    "Italie",
    "Kosovo",
    "Macédoine",
    "Macédoine du Nord",
    "Malte",
    "Monténégro",
    "Portugal",
    "Saint-Marin",
    "Serbie",
    "Slovénie",
    "Vatican",
]

EASTERN_EUROPE = [
    "Biélorussie",
    "Moldavie",
    "Pologne",
    "République tchèque",
    "Roumanie",
    "Slovaquie",
    "Ukraine",
    "Russie",
]

NORTH_AFRICA = [
    "Algérie",
    "Égypte",
    "Libye",
    "Maroc",
    "Soudan",
    "Tunisie",
]

WEST_AFRICA = [
    "Bénin",
    "Burkina Faso",
    "Cap-Vert",
    "Côte d'Ivoire",
    "Gambie",
    "Ghana",
    "Guinée",
    "Guinée-Bissau",
    "Liberia",
    "Mali",
    "Mauritanie",
    "Niger",
    "Nigeria",
    "Sénégal",
    "Sierra Leone",
    "Togo",
]

CENTRAL_AFRICA = [
    "Angola",
    "Burundi",
    "Cameroun",
    "République centrafricaine",
    "République du Congo",
    "République démocratique du Congo",
    "Gabon",
    "Guinée équatoriale",
    "Rwanda",
    "São Tomé-et-Principe",
    "Tchad",
]

EAST_AFRICA = [
    "Comores",
    "Djibouti",
    "Érythrée",
    "Éthiopie",
    "Kenya",
    "Madagascar",
    "Malawi",
    "Maurice",
    "Mozambique",
    "Ouganda",
    "Seychelles",
    "Somalie",
    "Soudan du Sud",
    "Tanzanie",
    "Zambie",
    "Zimbabwe",
]

SOUTHERN_AFRICA = [
    "Afrique du Sud",
    "Botswana",
    "Eswatini",
    "Lesotho",
    "Namibie",
]

MIDDLE_EAST = [
    "Arabie saoudite",
    "Bahreïn",
    "Émirats arabes unis",
    "Irak",
    "Iran",
    "Israël",
    "Jordanie",
    "Koweït",
    "Liban",
    "Oman",
    "Palestine",
    "Qatar",
    "Syrie",
    "Turquie",
    "Yémen",
]

CENTRAL_ASIA = [
    "Afghanistan",
    "Kazakhstan",
    "Kirghizistan",
    "Ouzbékistan",
    "Tadjikistan",
    "Turkménistan",
]

EAST_ASIA = [
    "Chine",
    "Corée du Nord",
    "Corée du Sud",
    "Japon",
    "Mongolie",
    "Taïwan",
]

SOUTH_ASIA = [
    "Bangladesh",
    "Bhoutan",
    "Inde",
    "Maldives",
    "Népal",
    "Pakistan",
    "Sri Lanka",
]

SOUTHEAST_ASIA = [
    "Birmanie",
    "Brunei",
    "Cambodge",
    "Indonésie",
    "Laos",
    "Malaisie",
    "Philippines",
    "Singapour",
    "Thaïlande",
    "Timor oriental",
    "Viêt Nam",
]

CAUCASUS = [
    "Abkhazie",
    "Arménie",
    "Azerbaïdjan",
    "Géorgie",
    "Ossétie du Sud-Alanie",
]

ANGLO_AMERICA = [
    "Canada",
    "États-Unis",
]

CENTRAL_AMERICA = [
    "Belize",
    "Costa Rica",
    "Guatemala",
    "Honduras",
    "Mexique",
    "Nicaragua",
    "Panama",
    "Salvador",
]

CARIBBEAN = [
    "Antigua-et-Barbuda",
    "Bahamas",
    "Barbade",
    "Cuba",
    "Dominique",
    "Grenade",
    "Haïti",
    "Jamaïque",
    "République dominicaine",
    "Saint-Christophe-et-Niévès",
    "Sainte-Lucie",
    "Saint-Vincent-et-les Grenadines",
    "Trinité-et-Tobago",
]

SOUTH_AMERICA = [
    "Argentine",
    "Bolivie",
    "Brésil",
    "Chili",
    "Colombie",
    "Équateur",
    "Guyana",
    "Paraguay",
    "Pérou",
    "Suriname",
    "Uruguay",
    "Venezuela",
]

AUSTRALASIA = [
    "Australie",
    "Nouvelle-Zélande",
]

MELANESIA = [
    "Fidji",
    "Papouasie-Nouvelle-Guinée",
    "Îles Salomon",
    "Vanuatu",
]

MICRONESIA = [
    "Kiribati",
    "Îles Marshall",
    "Micronésie",
    "Nauru",
    "Palaos",
]

POLYNESIA = [
    "Îles Cook",
    "Niue",
    "Samoa",
    "Tonga",
    "Tuvalu",
]

LIST_OF_REGIONS = [
    NORTHERN_EUROPE,
    WESTERN_EUROPE,
    SOUTHERN_EUROPE,
    EASTERN_EUROPE,
    NORTH_AFRICA,
    WEST_AFRICA,
    CENTRAL_AFRICA,
    EAST_AFRICA,
    SOUTHERN_AFRICA,
    MIDDLE_EAST,
    CENTRAL_ASIA,
    EAST_ASIA,
    SOUTH_ASIA,
    SOUTHEAST_ASIA,
    CAUCASUS,
    ANGLO_AMERICA,
    CENTRAL_AMERICA,
    CARIBBEAN,
    SOUTH_AMERICA,
    AUSTRALASIA,
    MELANESIA,
    MICRONESIA,
    POLYNESIA,
]


MINIMAL_PRECISSENES_SCORE: int = 650
LIST_OF_REAL_PEOPLE_FILEPATH: str = "list_of_wikipedia_page_of_real_people.txt"

HISTORICAL_PERIODS = [
    "Prehistory",
    "Antiquity",
    "Middle Ages",
    "Renaissance",
    "Contemporary Period",
    "Today Time"
]

HISTORICAL_PERIODS_TIME = [
    "-99999"
    "-3300",
    "476",
    "1492",
    "1789",
    "2000"
]
