"""A file that contain all global variable"""

MONTH_TO_NUMBER_DICT: dict[str, str] = {
    "janvier": "01",
    "fevrier": "02",
    "février": "02",
    "mars": "03",
    "avril": "04",
    "mai": "05",
    "juin": "06",
    "juillet": "07",
    "aout": "08",
    "août": "08",
    "septembre": "09",
    "octobre": "10",
    "novembre": "11",
    "decembre": "12",
    "décembre": "12"
}

NUMBER_TO_MONTH_DICT: dict[str, str] = {
    "01": "janvier",
    "02": "février",
    "03": "mars",
    "04": "avril",
    "05": "mai",
    "06": "juin",
    "07": "juillet",
    "08": "août",
    "09": "septembre",
    "10": "octobre",
    "11": "novembre",
    "12": "décembre",
}

LIST_OF_MONTH: list[str] = [
    "janvier",
    "février",
    "mars",
    "avril",
    "mai",
    "juin",
    "juillet",
    "août",
    "septembre",
    "octobre",
    "novembre",
    "décembre",
]

ABSOLUTE_DATE_VALUE: int = 1000000

AFRICA: list[str] = [
    "afrique du sud",
    "algérie",
    "angola",
    "bénin",
    "botswana",
    "burkina faso",
    "burundi",
    "cameroun",
    "cap-vert",
    "république centrafricaine",
    "comores",
    "république du congo",
    "république démocratique du congo",
    "côte d'ivoire",
    "djibouti",
    "égypte",
    "érythrée",
    "eswatini",
    "éthiopie",
    "gabon",
    "gambie",
    "ghana",
    "guinée",
    "guinée-bissau",
    "guinée équatoriale",
    "kenya",
    "lesotho",
    "liberia",
    "libye",
    "madagascar",
    "malawi",
    "mali",
    "maroc",
    "maurice",
    "mauritanie",
    "mozambique",
    "namibie",
    "niger",
    "nigeria",
    "ouganda",
    "rwanda",
    "são tomé-et-principe",
    "sénégal",
    "seychelles",
    "sierra leone",
    "somalie",
    "soudan",
    "soudan du sud",
    "tanzanie",
    "tchad",
    "togo",
    "tunisie",
    "zambie",
    "zimbabwe"
]

AMERICA: list[str] = [
    "antigua-et-barbuda",
    "argentine",
    "bahamas",
    "barbade",
    "belize",
    "bolivie",
    "brésil",
    "canada",
    "chili",
    "colombie",
    "costa rica",
    "cuba",
    "république dominicaine",
    "dominique",
    "équateur",
    "états-unis",
    "grenade",
    "guatemala",
    "guyana",
    "haïti",
    "honduras",
    "jamaïque",
    "mexique",
    "nicaragua",
    "panama",
    "paraguay",
    "pérou",
    "saint-christophe-et-niévès",
    "saint-vincent-et-les grenadines",
    "sainte-lucie",
    "salvador",
    "suriname",
    "trinité-et-tobago",
    "uruguay",
    "venezuela"
]

ASIA: list[str] = [
    "abkhazie",
    "afghanistan",
    "arabie saoudite",
    "arménie",
    "azerbaïdjan",
    "bahreïn",
    "bangladesh",
    "bhoutan",
    "birmanie",
    "brunei",
    "cambodge",
    "chine",
    "chypre",
    "chypre du nord",
    "corée du nord",
    "corée du sud",
    "émirats arabes unis",
    "géorgie",
    "inde",
    "indonésie",
    "irak",
    "iran",
    "israël",
    "japon",
    "jordanie",
    "kazakhstan",
    "kirghizistan",
    "koweït",
    "laos",
    "liban",
    "malaisie",
    "maldives",
    "mongolie",
    "népal",
    "oman",
    "ossétie du sud-alanie",
    "ouzbékistan",
    "pakistan",
    "palestine",
    "philippines",
    "qatar",
    "russie",
    "singapour",
    "sri lanka",
    "syrie",
    "tadjikistan",
    "taïwan",
    "taiwan"
    "thaïlande",
    "timor oriental",
    "turkménistan",
    "turquie",
    "viêt nam",
    "yémen"
]

EUROPE: list[str] = [
    "albanie",
    "allemagne",
    "andorre",
    "angleterre",
    "autriche",
    "belgique",
    "biélorussie",
    "bosnie-herzégovine",
    "bulgarie",
    "croatie",
    "danemark",
    "écosse",
    "espagne",
    "estonie",
    "finlande",
    "france",
    "grèce",
    "hongrie",
    "irlande",
    "irlande du nord",
    "islande",
    "italie",
    "kosovo",
    "lettonie",
    "liechtenstein",
    "lituanie",
    "luxembourg",
    "macédoine",
    "macédoine du nord",
    "malte",
    "moldavie",
    "monaco",
    "monténégro",
    "norvège",
    "pays-bas",
    "pays de galles",
    "pologne",
    "portugal",
    "roumanie",
    "royaume-uni",
    "saint-marin",
    "serbie",
    "slovaquie",
    "slovénie",
    "suède",
    "suisse",
    "république tchèque",
    "ukraine",
    "vatican"
]

OCEANIA: list[str] = [
    "australie",
    "fidji",
    "îles cook",
    "kiribati",
    "îles marshall",
    "micronésie",
    "nauru",
    "niue",
    "nouvelle-zélande",
    "palaos",
    "papouasie-nouvelle-guinée",
    "îles salomon",
    "samoa",
    "tonga",
    "tuvalu",
    "vanuatu"
]

LIST_OF_REGIONS_NAME = [
    "Europe du Nord",
    "Europe de l'Ouest",
    "Europe du Sud",
    "Europe de l'Est",
    "Afrique du Nord",
    "Afrique de l'Ouest",
    "Afrique centrale",
    "Afrique de l'Est",
    "Afrique australe",
    "Moyen-Orient",
    "Asie centrale",
    "Asie de l'Est",
    "Asie du Sud",
    "Asie du Sud-Est",
    "Caucase",
    "Amérique anglo-saxonne",
    "Amérique centrale",
    "Caraïbes",
    "Amérique du Sud",
    "Australasie",
    "Mélanésie",
    "Micronésie",
    "Polynésie",
]
LIST_OF_CONTINENTS: list[str] = [AFRICA,AMERICA,ASIA,EUROPE,OCEANIA]

JOBS: list[str] = [
    "Biathlète",
    "Ingénieur",
    "Empereur",
    "Roi",
    "Reine",
    "Général",
    "auteur-compositeur-interprète",
    "Skipper",
    "Surfeur",
    "Résistant",
    "Résistante",
    "Empereur romain"
    "Skieur",
    "Géologue",
    "Vicaire",
    "Expert-comptable",
    "Escrimeuse",
    "Évêque d'Orléans",
    "Général",
    "Golfeur",
    "Skieuse",
    "Tireuse",
    "Pharmacologue",
    "Fondeuse"
    "Écrivain",
    "Auteur",
    "Romancier",
    "Poète",
    "Essayiste",
    "Musicien",
    "Journaliste",
    "Réalisateur",
    "Producteur de cinéma",
    "Scénariste",
    "Acteur",
    "Actrice",
    "Chanteur",
    "Chanteuse",
    "Musicien",
    "Compositeur",
    "Parolier",
    "Producteur musical",
    "Artiste",
    "Peintre",
    "Sculpteur",
    "Photographe",
    "Architecte",
    "Designer",
    "Illustrateur",
    "Dessinateur",
    "Humoriste",
    "Comédien",
    "Présentateur de télévision",
    "Animateur de radio",
    "Animateur de télévision",
    "Mannequin",
    "Danseur",
    "Chorégraphe",
    "Acteur de théâtre",
    "Metteur en scène",
    "Dramaturge",
    "Historien",
    "Philosophe",
    "Sociologue",
    "Anthropologue",
    "Linguiste",
    "Chercheur",
    "Scientifique",
    "Physicien",
    "Chimiste",
    "Mathématicien",
    "Biologiste",
    "Médecin",
    "Psychiatre",
    "Inventeur",
    "Ingénieur",
    "Informaticien",
    "Développeur",
    "Entrepreneur",
    "Homme d'affaires",
    "Femme d'affaires",
    "Industriel",
    "Banquier",
    "Économiste",
    "Juriste",
    "Avocat",
    "Magistrat",
    "Diplomate",
    "Militaire",
    "Officier",
    "Explorateur",
    "Aventurier",
    "Athlète",
    "Footballeur",
    "Basketteur",
    "Tennisman",
    "Pilote automobile",
    "Pilote d'avion",
    "Sportif",
    "Entraîneur sportif",
    "Joueur d'échecs",
    "Chef cuisinier",
    "Cuisinier",
    "Architecte paysagiste",
    "Religieux",
    "Théologien",
    "Prêtre",
    "Moine",
    "Activiste",
    "Militant",
    "Homme politique",
    "Femme politique",
    "Homme d'État"
    "Femme d'État"
    "Député",
    "Président",
    "Premier ministre",
    "Roi",
    "Reine",
    "Prince",
    "Professeur",
    "Enseignant",
    "Universitaire",
    "Critique littéraire",
    "Critique d'art",
    "Éditeur",
    "Souverain",
    "Prêtre catholique",
    "Claveciniste",
    "Auteur de jeux de société",
    "Prêtre orthodoxe",
    "Ayatollah",
    "Conteur",
    "Pianiste",
    "Personnalité politique",
    "Infirmier",
    "Saxophoniste",
    "Cadi",
    "Personnalité du monde des affaires",
    "Pilote (aviation)",
    "Charpentier",
    "Rabbin",
    "Artiste peintre",
    "Ingénieur civil",
    "Lama (bouddhisme)",
    "Astronome",
    "Maître spirituel",
    "Botaniste",
    "Violoncelliste",
    "Maréchal",
    "Commissaire aux comptes",
    "Groupie",
    "Artiste lyrique",
    "Défenseur des droits de l'homme",
    "Arbitre (football)",
    "Haute fonction publique",
    "Potier (métier)",
    "Vizir",
    "Auteur-compositeur",
    "Syndicaliste",
    "Guitariste",
    "Évêque catholique",
    "Troubadour",
    "Mangaka",
    "Psychologue",
    "Altiste",
    "Illusionniste",
    "Instituteur",
    "Avocat (métier)",
    "Pasteur (christianisme)",
    "Producteur de télévision",
    "Directeur de la photographie",
    "Financier",
    "Urgentiste",
    "Barde (poète gael)",
    "Graphiste",
    "Homme politique",
    "Femme politique"
    "Disc jockey",
    "Chef d'orchestre",
    "Maître écrivain",
    "Consultant",
    "Caricaturiste",
    "Peintre de cour",
    "Corsaire",
    "Styliste",
    "Harpiste",
    "Metteur en scène",
    "Créateur de caractères",
    "Sculpteur",
    "Influenceur web",
    "Marchand d'art",
    "Vitrailliste",
    "Administrateur colonial",
    "Homme d'État",
    "Attachée de presse",
    "Policier",
    "Entomologiste",
    "Marchand (commerce)",
    "Mannequin",
    "Musicien électronique",
    "Plasticien",
    "Sage-femme",
    "Artiste contemporain",
    "Capitaine de navire",
    "Réalisateur de télévision",
    "Chroniqueur (littéraire)",
    "Abbesse",
    "Violoniste",
    "Publiciste",
    "Sexologue",
    "Trompettiste",
    "Ingénieur du son",
    "Critique de cinéma",
    "Patineur artistique",
    "Artiste plasticienne",
    "Acteur de doublage",
    "Cascadeur",
    "Journaliste sportif",
    "Torero",
    "Fleuriste",
    "Archiviste",
    "Bassiste",
    "Chercheur universitaire",
    "Chercheur en",
    "Président",
    "Présidente"
    "Chercheuse en",  
    "Restaurateur d'art",
    "Dessinateur humoristique",
    "Librettiste",
    "Dialoguiste",
    "Cryptographe",
    "Musicologue",
    "Parasitologue",
    "Anthropologue",
    "Reporter",
    "Conquistador",
    "Producteur de radio",
    "Paysagiste",
    "Chirurgien",
    "Agriculteur",
    "Heilpraktiker",
    "Vigneron",
    "Pilote (profession maritime)",
    "Directeur de casting",
    "Modiste",
    "Naturaliste",
    "Cow-boy",
    "Sommelier",
    "Monteur son",
    "Luthier",
    "Éleveur équin",
    "Historien",
    "Historien de la philosophie",
    "Humoriste",
    "Pharmacien",
    "Pâtissier",
    "Parfumeur",
    "Jardinier",
    "Guide de haute montagne",
    "Narrateur",
    "Horloger",
    "Navigateur (marine)",
    "Architecte naval",
    "Seigneur de guerre",
    "Juge",
    "Conservateur de musée",
    "Conservateur du patrimoine",
    "Relieur",
    "Photographe",
    "Orfèvre",
    "Notaire",
    "Entrepreneur",
    "Directeur des ressources humaines",
    "Commissaire d'exposition",
    "Bassoniste",
    "Tromboniste",
    "Tailleur de pierre",
    "Viticulteur",
    "Écuyer",
    "Libraire",
    "Fonctionnaire impérial",
    "Zoologiste",
    "Photographe plasticien",
    "Agent de renseignement",
    "Maquilleur",
    "Conducteur de train",
    "Vacher",
    "Instrumentiste",
    "Ingénieur logiciel",
    "Radioamateur",
    "Espion",
    "Maître à danser",
    "Facteur d'orgues",
    "Affichiste",
    "Éditeur (métier)",
    "Armateur",
    "Corniste",
    "Sénéchal",
    "Microbiologiste",
    "Facteur de pianos",
    "Barrister",
    "Reporter-photographe",
    "Statisticien",
    "Monteur",
    "Coiffeur",
    "Skipper",
    "Professeur documentaliste",
    "Sommelier",
    "Coiffeur",
    "Professeur (enseignant)",
    "Investisseur",
    "Docteur en médecine",
    "Vidéaste web",
    "Artiste de rue",
    "Géographe",
    "Tueur à gages",
    "Intelligence artificielle (chercheur)",
    "Busshi",
    "Chaman",
    "Boulanger",
    "Écrivain voyageur",
    "Dessinateur de bande dessinée",
    "Scénariste de bande dessinée",
    "Président-directeur général",
    "Scribe",
    "Youtubeur virtuel",
    "Directeur littéraire",
    "Producteur de cinéma",
    "Chef militaire",
    "Illustrateur botanique",
    "Lexicographe",
    "Fondeur de cloches",
    "Productrice de cinéma",
    "Directeur artistique",
    "Correspondant local de presse",
    "Tatoueur",
    "Modèle (art)",
    "Pathologiste",
    "Écrivain public",
    "Critique de vin",
    "Promoteur immobilier",
    "Dirigeant",
    "Sommelier",
    "Lissier",
    "Professeur documentaliste",
    "Chocolatier",
    "Horloger",
    "Architecte",
    "Marin (profession)",
    "Assistant réalisateur",
    "Typographe",
    "Écrivaine",
    "Reporter",
    "Conquistador",
    "Griot",
    "Photographe de mode",
    "Monteur",
    "Dramaturge",
    "Professeur",
    "Superviseur des effets visuels",
    "Producteur de jeux vidéo",
    "Maquilleur",
    "Paysagiste",
    "Chocolatier",
    "Tailleur de pierre",
    "Chef de chœur",
    "Correspondant de guerre",
    "Chef opérateur",
    "Directeur de théâtre",
    "Marin",
    "Skipper",
    "Viticulteur",
    "Conseiller d'État",
    "Trésorier",
    "Agent de change",
    "Forgeron",
    "Art numérique (artiste)",
    "Fondeur",
    "Ingénieur militaire",
    "Ingénieur agronome",
    "Urbaniste",
    "Spin doctor",
    "Chef de produit",
    "Trésorier (comptabilité)",
    "Directeur",
    "Chef d'entreprise",
    "Restaurateur",
    "Banquier d'affaires",
    "Conservateur du patrimoine",
    "Relieur",
    "Pharmacien",
    "Marchand mercier",
    "Jardinier",
    "Capitaine",
    "Docteur",
    "Scientifique",
    "Programmeur",
    "Développeur",
    "Ingénieur",
    "Autrice",
    "Romancière",
    "Poétesse",
    "Essayiste",  # épicène
    "Musicienne",
    "Journaliste",  # épicène
    "Réalisatrice",
    "Productrice musicale",
    "Compositrice",
    "Parolière",
    "Peintre",  # épicène
    "Sculptrice",
    "Photographe",  # épicène
    "Architecte",  # épicène
    "Designeuse",
    "Illustratrice",
    "Dessinatrice",
    "Humoriste",  # épicène
    "Comédienne",
    "Présentatrice de télévision",
    "Animatrice de radio",
    "Animatrice de télévision",
    "Danseuse",
    "Chorégraphe",  # épicène
    "Actrice de théâtre",
    "Metteuse en scène",
    "Historienne",
    "Philosophe",  # épicène
    "Sociologue",  # épicène
    "Anthropologue",  # épicène
    "Linguiste",  # épicène
    "Chercheuse",
    "Scientifique",  # épicène
    "Physicienne",
    "Chimiste",
    "Mathématicienne",
    "Biologiste",
    "Médecin",  # épicène
    "Psychiatre",  # épicène
    "Inventrice",
    "Ingénieure",
    "Informaticienne",
    "Développeuse",
    "Entrepreneuse",
    "Industrielle",
    "Banquière",
    "Économiste",  # épicène
    "Juriste",  # épicène
    "Avocate",
    "Magistrate",
    "Diplomate",  # épicène
    "Militaire",  # épicène
    "Officière",
    "Exploratrice",
    "Aventurière",
    "Athlète",  # épicène
    "Footballeuse",
    "Basketteuse",
    "Joueuse de tennis",
    "Pilote automobile",  # épicène
    "Pilote d'avion",  # épicène
    "Sportive",
    "Entraîneuse sportive",
    "Joueuse d'échecs",
    "Cheffe cuisinière",
    "Cuisinière",
    "Religieuse",
    "Théologienne",
    "Prêtresse",
    "Moniale",
    "Activiste",  # épicène
    "Militante",
    "Députée",
    "Présidente",
    "Première ministre",
    "Princesse",
    "Professeure",
    "Enseignante",
    "Universitaire",  # épicène
    "Critique littéraire",  # épicène
    "Critique d'art",  # épicène
    "Éditrice",
    "Souveraine",
    "Claveciniste",  # épicène
    "Autrice de jeux de société",
    "Conteuse",
    "Pianiste",  # épicène
    "Personnalité politique",  # épicène
    "Infirmière",
    "Saxophoniste",  # épicène
    "Cadie",
    "Charpentière",
    "Rabbine",
    "Astronome",  # épicène
    "Botaniste",  # épicène
    "Violoncelliste",  # épicène
    "Commissaire aux comptes",  # épicène
    "Artiste lyrique",  # épicène
    "Défenseuse des droits de l'homme",
    "Arbitre",
    "Potière",
    "Autrice-compositrice",
    "Syndicaliste",  # épicène
    "Guitariste",  # épicène
    "Mangaka",  # épicène
    "Psychologue",  # épicène
    "Altiste",  # épicène
    "Illusionniste",  # épicène
    "Institutrice",
    "Productrice de télévision",
    "Directrice de la photographie",
    "Financière",
    "Urgentiste",  # épicène
    "Graphiste",  # épicène
    "Disc-jockey",
    "Cheffe d'orchestre",
    "Consultante",
    "Caricaturiste",  # épicène
    "Peintre de cour",  # épicène
    "Corsaire",  # épicène
    "Créatrice de caractères",
    "Influenceuse web",
    "Marchande d'art",
    "Vitrailliste",  # épicène
    "Administratrice coloniale",
    "Policière",
    "Entomologiste",  # épicène
    "Marchande",
    "Musicienne électronique",
    "Plasticienne",
    "Capitaine de navire",  # épicène
    "Réalisatrice de télévision",
    "Chroniqueuse",
    "Publicitaire",
    "Sexologue",  # épicène
    "Trompettiste",  # épicène
    "Ingénieure du son",
    "Critique de cinéma",  # épicène
    "Patineuse artistique",
    "Actrice de doublage",
    "Cascadeuse",
    "Journaliste sportive",
    "Fleuriste",  # épicène
    "Archiviste",  # épicène
    "Bassiste",  # épicène
    "Chercheuse universitaire",
    "Restauratrice d'art",
    "Dessinatrice humoristique",
    "Librettiste",  # épicène
    "Directrice générale",
    "Dialoguiste",  # épicène
    "Cryptographe",  # épicène
    "Musicologue",  # épicène
    "Parasitologue",  # épicène
    "Reporteuse",
    "Chirurgienne",
    "Agricultrice",
    "Vigneronne",
    "Directrice de casting",
    "Naturaliste",  # épicène
    "Cow-girl",
    "Sommelière",
    "Monteuse son",
    "Luthière",
    "Éleveuse équine",
    "Pharmacienne",
    "Pâtissière",
    "Parfumeuse",
    "Jardinière",
    "Guide de haute montagne",  # épicène
    "Narratrice",
    "Horlogère",
    "Navigatrice",
    "Juge",  # épicène
    "Conservatrice de musée",
    "Conservatrice du patrimoine",
    "Relieuse",
    "Orfèvre",  # Orfévesse est très rare
    "Notaire",  # épicène
    "Directrice des ressources humaines",
    "Commissaire d'exposition",  # épicène
    "Bassoniste",  # épicène
    "Tromboniste",  # épicène
    "Tailleuse de pierre",
    "Viticultrice",
    "Écuyère",
    "Libraire",  # épicène
    "Zoologiste",  # épicène
    "Photographe plasticienne",
    "Agente de renseignement",
    "Maquilleuse",
    "Conductrice de train",
    "Vachère",
    "Instrumentiste",  # épicène
    "Ingénieure logiciel",
    "Espionne",
    "Affichiste",  # épicène
    "Éditrice",
    "Armatrice",
    "Corniste",  # épicène
    "Microbiologiste",  # épicène
    "Factrice de pianos",
    "Statisticienne",
    "Monteuse",
    "Coiffeuse",
    "Skipeuse",
    "Professeure documentaliste",
    "Investisseuse",
    "Docteure en médecine",
    "Vidéaste web",  # épicène
    "Boulangère",
    "Écrivaine voyageuse",
    "Dessinatrice de bande dessinée",
    "Scénariste de bande dessinée",  # épicène
    "Présidente-directrice générale",
    "Scribe",  # épicène
    "Youtubeuse virtuelle",
    "Directrice littéraire",
    "Cheffe militaire",
    "Illustratrice botanique",
    "Lexicographe",  # épicène
    "Directrice artistique",
    "Correspondante locale de presse",
    "Tatoueuse",
    "Pathologiste",  # épicène
    "Écrivaine publique",
    "Critique de vin",  # épicène
    "Promotrice immobilière",
    "Dirigeante",
    "Lissière",
    "Assistante réalisatrice",
    "Typographe",  # épicène
    "Griotte",
    "Photographe de mode",  # épicène
    "Superviseuse des effets visuels",
    "Productrice de jeux vidéo",
    "Cheffe de chœur",
    "Correspondante de guerre",
    "Cheffe opératrice",
    "Directrice de théâtre",
    "Marinière",
    "Conseillère d'État",
    "Trésorière",
    "Agente de change",
    "Forgeronne",
    "Fondeuse",
    "Ingénieure militaire",
    "Ingénieure agronome",
    "Urbaniste",  # épicène
    "Cheffe de produit",
    "Trésorière (comptabilité)",
    "Directrice",
    "Cheffe d'entreprise",
    "Restauratrice",
    "Banquière d'affaires",
    "Programmeuse",
     "Antiquaire",
    "Apiculteur",
    "Apicultrice",
    "Archer",
    "Archère",
    "Archevêque",
    "Artiste-peintre",
    "Armurier",
    "Armurière",
    "Auteur de littérature pour la jeunesse",
    "Autrice de littérature pour la jeunesse",
    "Auteur-compositeur-interprète",
    "Autrice-compositrice-interprète",
    "Autrice-compositrice-interprète",
    "Banderillero",
    "Banderillera",
    "Bandit",
    "Bandite",
    "Berger",
    "Bergère",
    "Bienheureux",
    "Bienheureuse",
    "Bushi",
    "Calligraphe",
    "Chapelain",
    "Chapelaine",
    "Chanoinesse",
    "Chorévêque",
    "Choriste",
    "Colonel",
    "Collectionneur",
    "Collectionneuse",
    "Concepteur de jeu",
    "Conceptrice de jeu",
    "Conseiller Pôle emploi",
    "Conseillère Pôle emploi",
    "Contrebandier",
    "Contrebandière",
    "Courtisan",
    "Courtisane",
    "Cyberdissident",
    "Cyberdissidente",
    "Diariste",
    "Doge",
    "Drogman",
    "Duc",
    "Duchesse",
    "Escroc",
    "Escroque",
    "Évêque",
    "Fonctionnaire",
    "Folkloriste",
    "Généticien",
    "Généticienne",
    "Gentilhomme",
    "Gentilfemme",
    "Gladiateur",
    "Gladiatrice",
    "Graveur sur cuivre",
    "Graveuse sur cuivre",
    "Haut fonctionnaire",
    "Haute fonctionnaire",
    "Horticulteur",
    "Horticultrice",
    "Hydrographe",
    "Imprimeur",
    "Imprimeuse",
    "Interprète",
    "Lama",
    "Lobbyiste",
    "Manhwaga",
    "Margrave",
    "Menuisier",
    "Menuisière",
    "Ministre",
    "Modéliste",
    "Ninja",
    "Nourrice",
    "Orateur",
    "Oratrice",
    "Pasteur",
    "Pasteure",
    "Plâtrier",
    "Plâtrière",
    "Prélat",
    "Prêtresse catholique",
    "Professeur d'université",
    "Professeure d'université",
    "Rappeur",
    "Rappeuse",
    "Réalisateur de cinéma",
    "Réalisatrice de cinéma",
    "Réalisateur artistique",
    "Réalisatrice artistique",
    "Rosh yeshiva",
    "Scalde",
    "Serrurier",
    "Serrurière",
    "Soldat",
    "Soldate",
    "Solliciteur",
    "Sollicitrice",
    "Soudeur",
    "Soudeuse",
    "Sophiste",
    "Sous-diacre",
    "Sultan",
    "Sultane",
    "Tailleur",
    "Tailleuse",
    "Tlatoani",
    "Trouvère",
    "Trouveresse",
    "Vétérinaire",
    "Vogt",
    "Volcanologue",
    "Bhikkhuni"
]

CITIES: list[str] = [
    "Houston",
    "Marseille",
    "Alger",
    "Ouagadougou",
    "Dakar",
    "Bamberg",
    "Vérone",
    "Orléans",
    "Netzschkau",
    "Nagercoil",
    "Ascain",
    "Apt",
    "Pau",
    "Wilchingen"
    "Abidjan",
    "Auxerre",
    "Onitsha",
    "Brisbane",
    "Dwikozy",
    "Southsea",
    "Ulm",
    "Marles-les-Mines"
    "Cebreros",
    "Montoire-sur-le-Loir",
    "Pulsnitz",
    "Villeurbanne",
    "Noranda"
    "Bongouanou",
    "Meilen",
    "Potsdam",
    "Yaté",
    "Hollerich",
    "Ribeauvillé",
    "Bogota",
    "Rome",
    "Paris",
    "Rosières",
    "Montréal",
    "Chicoutimi",
    "Roura",
    "Aoste",
    "Munich",
    "Lille",
    "Namur",
    "Meknès",
    "Tanger",
    "Tizi Ouzou",
    "Tan-Tan",
    "Nzérékoré",
    "Philadelphie",
    "Vesoul",
    "Nîmes",
    "Bourg-en-Bresse",
    "Lannion",
    "Saïgon",
    "Douala",
    "Nanterre",
    "Schaerbeek",
    "Tivoli",
    "Hambourg",
    "Männedorf",
    "Bordeaux",
    "Garnsee",
    "Reims",
    "Meißen",
    "Zurich",
    "Coppet",
    "Bône",
    "Salmaise",
    "Genève",
    "Budapest",
    "Francfort-sur-le-Main",
    "Wurtzbourg",
    "Eichstätt",
    "Näples",
    "Barranquilla",
    "Königsberg",
    "Berlin",
    "Berlin-Spandau",
    "Aberdeen",
    "Lausanne",
    "Drummondville",
    "Annemasse",
    "Moscou",
    "Saint-Pierre-en-Val",
    "Port-au-Prince",
    "Vincennes",
    "Colmar",
    "Chartres",
    "Anduze",
    "Weimar",
    "Sydney",
    "Nazareth",
    "Zanzibar",
    "Shanghai",
    "Charquemont",
    "Fatick",
    "Meyrin",
    "Aix-en-Provence",
    "Kaunas",
    "Montemor-o-Novo",
    "Ploudalmézeau",
    "Amiens",
    "Néfiach",
    "Saint-Jean",
    "Linguère",
    "Bolton",
    "Louga",
    "Naplouse",
    "Zacatecas",
    "Stendal",
    "Saint-Pierre-de-Sorel",
    "Libreville",
    "Bignona",
    "Tournai",
    "Santos",
    "Avallon",
    "Aarhus",
    "Bologne",
    "Belluno",
    "Santiago",
    "Venise",
    "Amberg",
    "Aalen",
    "Lviv",
    "Chełm Śląski",
    "Gourdinne",
    "Rivesaltes",
    "Victoriaville",
    "Marnes-la-Coquette",
    "Tchortkiv",
    "Saint-Julien-en-Born",
    "Wamba",
    "Fréjus",
    "Commercy",
    "Yzeure",
    "Lunel",
    "Maastricht",
    "Rhyl",
    "Chicago",
    "Greifswald",
    "Calvi",
    "Crémone",
    "Londres",
    "Frederiksberg",
    "Asciano",
    "Dubăsari",
    "Saint-Mihiel",
    "Denain",
    "Lyon",
    "Saint-Avold",
    "Puylaurens",
    "Poperinge",
    "Helsinki",
    "Cambrai",
    "Lübeck",
    "Mantes-la-Ville",
    "Holwierde",
    "Saint-Étienne",
    "Boma",
    "Boston",
    "Kiel",
    "Strasbourg",
    "Bruxelles",
    "Charleroi",
    "Lunéville",
    "Vienne",
    "Salzbourg",
    "Copenhague",
    "Salon-de-Provence",
    "Milan",
    "Campobasso",
    "Montevideo",
    "Messine",
    "Antananarivo",
    "Cyrène",
    "Angers",
    "Saint-Nicolas-d'Aliermont",
    "Durango",
    "Perpignan",
    "Nevers",
    "Vichy",
    "Dresde",
    "Brünn",
    "Prague",
    "Beyrouth",
    "Kyoustendil",
    "Téhéran",
    "Culhuacan",
    "Wetzlar",
    "Stargard",
    "Champsecret",
    "Neuchâtel",
    "Quimper",
    "Nyon",
    "Ensival",
    "Besançon",
    "Darmstadt",
    "Vilvorde",
    "Rotterdam",
    "Conques",
    "Orange",
    "Las Palmas de Gran Canaria",
    "Ankara",
    "Marsan",
    "Istanbul",
    "Bambey",
    "Épinay-sur-Seine",
    "Caracas",
    "Kinshasa",
    "Goma",
    "Bellinzone",
    "Porto-Novo",
    "Ostende",
    "Szamocin",
    "Morges",
    "Yamoussoukro",
    "Dunmurry",
    "Tacoma",
    "Pontevedra",
    "Galați",
    "Dunkerque",
    "Metz",
    "Kilkenny",
    "Tunis",
    "Toulouse",
    "Comè",
    "Biarritz",
    "Chantilly",
    "Wavre",
    "Saint-Paul-en-Jarez",
    "Firminy",
    "Macenta",
    "Orgerus",
    "Hof-sur-Saale",
    "Stralsund",
    "Vence",
    "Lorient",
    "Newark",
    "Yankton",
    "Linz",
    "Varsovie",
    "Bălți",
    "Saint",
    "Lecce",
    "Fredericton",
    "Dubrovnik",
    "Zagreb",
    "Winnipeg",
    "Mazamet",
    "Toronto",
    "Sieradz",
    "Livourne",
    "Boulogne-Billancourt",
    "Tallinn",
    "Oslo",
    "Springfield",
    "Essex",
    "Gassin",
    "Stockton-on-Tees",
    "Tournan-en-Brie",
    "Lassy",
    "Voujeaucourt",
    "Givors",
    "Maui",
    "Rheine",
    "Brême",
    "Trostberg",
    "Gransee",
    "Barcelone",
    "Florence",
    "Catanzaro",
    "Bissen",
    "Albacete",
    "Neuilly-sur-Seine",
    "Mexico",
    "Cles",
    "Gand",
    "Nice",
    "Ixelles",
    "Auffay",
    "Purmerland",
    "Douarnenez",
    "Uccle",
    "Frasnes-lez-Buissenal",
    "Sedan",
    "Iași",
    "Saint-Louis",
    "Brazzaville",
    "Saint-Nicolas",
    "Colombes",
    "Krefeld",
    "Leuze-en-Hainaut",
    "Rodez",
    "Carhaix-Plouguer",
    "Bronx",
    "Alost",
    "Épinal",
    "Hanoï",
    "Saint-Raymond",
    "Genlis",
    "Bondy",
    "Dole",
    "Burzaco",
    "Cúcuta",
    "Aubervilliers",
    "Bienne",
    "Brissago",
    "Antigonish",
    "Dortmund",
    "Lignol",
    "London",
    "Bucarest",
    "Burgos",
    "Sarreguemines",
    "Amsterdam",
    "Détroit",
    "Delémont",
    "Belfort",
    "Whitehorse",
    "Skopje",
    "Saint-Yrieix-la-Perche",
    "Gatineau",
    "Medellín",
    "Mont-Joli",
    "Kaolack",
    "Souleimaniye",
    "Boise",
    "Trois-Pistoles",
    "Hollywood",
    "Avranches",
    "Kangu",
    "Vinchio",
    "Il-Furjana",
    "Gijón",
    "Benghazi",
    "Saint-Denis",
    "Muralto",
    "Stuttgart",
    "Mayence",
    "Bocaiúva",
    "Addis-Abeba",
    "Cologne",
    "Villemoisson-sur-Orge",
    "Blois",
    "Reus",
    "Chișinău",
    "Kielce",
    "Richmond",
    "Bougouni",
    "Casablanca",
    "Fès",
    "Zhengzhou",
    "Bombay",
    "Sacramento",
    "Wiesbaden",
    "Pointe-à-Pitre",
    "Bamenda",
    "Vevey",
    "Berne",
    "Geseke",
    "Rio de Janeiro",
    "Halifax",
    "Dublin",
    "Elora",
    "Saint-Pétersbourg",
    "Lipcani",
    "Gênes",
    "Turin",
    "Gołdap",
    "Clervaux",
    "Bridgend",
    "Guéret",
    "Rougé",
    "Curitiba",
    "Pont-en-Royans",
    "LaSalle",
    "Leeds",
    "Remscheid",
    "Zwickau",
    "Brno",
    "Ramnäs",
    "Yaoundé",
    "Nancy",
    "Villarzel",
    "Frouard",
    "Lisbonne",
    "Leipzig",
    "Snowidza",
    "Schlieben",
    "Cassel",
    "Kleinobringen",
    "Vendenheim",
    "Anvers",
    "Nevele",
    "Casalmaggiore",
    "Crissier",
    "Malansac",
    "Laval",
    "Mbujimayi",
    "Carcassonne",
    "Alençon",
    "Rouen",
    "Ludwigshafen",
    "Béziers",
    "Fortaleza",
    "Gävle",
    "Grenoble",
    "Ladimirevci",
    "Gaziantep",
    "Tshikapa",
    "Parme",
    "Písek",
    "Craon",
    "Bytów",
    "Wessin",
    "Magdebourg",
    "Aplahoué",
    "Cholet",
    "Arleuf",
    "Garessio",
    "Ternitz",
    "Presbourg",
    "Évry-Courcouronnes",
    "Velika Kladuša",
    "Molfetta",
    "Butembo",
    "Dijon",
    "Sarrebourg",
    "São Paulo",
    "Cagnes-sur-Mer",
    "La Haye",
    "Crotone",
    "Charlesbourg",
    "Cognac",
    "León",
    "Zamora",
    "Valladolid",
    "Ivano-Frankivsk",
    "Limoges",
    "Lazise",
    "Brooklyn",
    "Dorsten",
    "Aix-la-Chapelle",
    "Achern",
    "Vallorbe",
    "Asmara",
    "Mirande",
    "Rennes",
    "Sète",
    "Brest",
    "Cap-Chat",
    "Luc-la-Primaube",
    "Douai",
    "Cuarny",
    "Ébreuil",
    "Clarmont",
    "Cracovie",
    "Olmütz",
    "Brugg",
    "Graz",
    "Hanovre",
    "Mannheim",
    "Wiltz",
    "Bobo-Dioulasso",
    "Villecresnes",
    "Brive-la-Gaillarde",
    "Pontedeume",
    "Bourg-Saint-Andéol",
    "Dambach-la-Ville",
    "Haine-Saint-Paul",
    "Lessines",
    "Oakland",
    "Pérouse",
    "Goilberdingen",
    "Vergt",
    "Bora-Bora",
    "Coire",
    "Baltimore",
    "Pasadena",
    "Indianapolis",
    "Kroppenstedt",
    "Abbeville",
    "Recife",
    "Erfurt",
    "Tianjin",
    "Amélie-les-Bains",
    "Cincinnati",
    "Lugano",
    "Merano",
    "Agde",
    "Athènes",
    "Brescia",
    "Corridonia",
    "Imola",
    "Gubbio",
    "Kyoto",
    "Jodhpur",
    "Bruges",
    "Vicence",
    "Roubaix",
    "Mascouche",
    "Stockholm",
    "Cossonay",
    "Fontainebleau",
    "Thoune",
    "Rimouski",
    "Trois-Rivières",
    "Sainte-Marie",
    "Val-d'Or",
    "Lagnieu",
    "Ennery",
    "Melun",
    "Suresnes",
    "Yogyakarta",
    "Taza",
    "Wörgl",
    "Carthage",
    "Bonn",
    "Raeren",
    "Versmold",
    "Malmö",
    "Bâle",
    "Appenzell",
    "Geisenheim",
    "Dallas",
    "Pula",
    "Sprottau",
    "Oranienbourg",
    "Glaris",
    "Kremsmünster",
    "Berlin-Siemensstadt",
    "Chester",
    "Neu-Ulm",
    "Bünde",
    "Longuefuye",
    "Luxeuil-les-Bains",
    "Valjouffrey",
    "Datteln",
    "Narbonne",
    "Bonchamp-lès-Laval",
    "Saint-André-les-Alpes",
    "Grimma",
    "Mauron",
    "Massachusetts",
    "Mauterndorf",
    "Wels",
    "Gnoien",
    "Kukës",
    "Limbourg-sur-la-Lahn",
    "Brwice",
    "Drożyna",
    "Strépy-Bracquegnies",
    "Thiers",
    "Tochigi",
    "Île des Pins",
    "Romans-sur-Isère",
    "Rusutsu",
    "Séoul",
    "Imintanoute",
    "Atlanta",
    "Pékin",
    "Longwy",
    "Bachhagel",
    "Akureyri",
    "Stettin",
    "Bielefeld",
    "Bissau",
    "Gdańsk",
    "Fanjeaux",
    "Arras",
    "Matanzas",
    "Omsk",
    "Yokohama",
    "Novohrad-Volynskyï",
    "Banja Luka",
    "Raubach",
    "Berlin-Schöneberg",
    "Tchernivtsi",
    "Passau",
    "Parakou",
    "Montpellier",
    "Maubeuge",
    "Kalocsa",
    "Reggio de Calabre",
    "Dnipropetrovsk",
    "Yverdon-les-Bains",
    "Cambrils",
    "Montargis",
    "Estagel",
    "Carmaux",
    "Chusclan",
    "Lutry",
    "Granville",
    "Cannes",
    "Saint-Maur-des-Fossés",
    "Aurillac",
    "Saint-Marcellin",
    "Hasparren",
    "Kapurthala",
    "Guayaquil",
    "Sofia",
    "Madrid",
    "Glasgow",
    "Hanna",
    "Saskatoon",
    "Rimini",
    "Palenque",
    "Soleure",
    "Saint-Jérôme",
    "Louny",
    "Cap de Trafalgar",
    "Loubressac",
    "Bonoua",
    "Sartène",
    "Porto-Vecchio",
    "Nantes",
    "Briançon",
    "Loos-en-Gohelle",
    "Civray",
    "Verdun",
    "Mulhouse",
    "Tirlemont",
    "Bapaume",
    "Sud-Kivu",
    "Niort",
    "Galéria",
    "Aignan",
    "Saint-Gilles",
    "Vernon",
    "Souchez",
    "Guengat",
    "Saint-Lô",
    "Warmeriville",
    "Valenciennes",
    "Louviers",
    "Kedgwick",
    "Quaregnon",
    "Fontoy",
    "Flacey-en-Bresse",
    "Périgueux",
    "Angoulême",
    "Poitiers",
    "Forbach",
    "Krattigen",
    "Beaune",
    "Frampton",
    "Berles-au-Bois",
    "Champniers-et-Reilhac",
    "Tours",
    "Bourges",
    "Astaffort",
    "Sainte-Eulalie-en-Born",
    "Rabat",
    "Nouméa",
    "Lapeyrouse",
    "Saint-Isidore",
    "Beauzac",
    "Saint-Sardos",
    "Coarraze",
    "Montivilliers",
    "Vittel",
    "Bastia",
    "Laon",
    "Pistoia",
    "Maisons-Laffitte",
    "Deshaies",
    "Riom",
    "Freetown",
    "Vejle",
    "Incheon",
    "Lima",
    "Eindhoven",
    "Pisco",
    "Dundee",
    "New York",
    "Liverpool",
    "Saint-Jean-sur-Richelieu",
    "Syracuse",
    "Berlin-Charlottenbourg",
    "Wilmington",
    "Saint Catharines",
    "Canterbury",
    "Alderley Edge",
    "Dukinfield",
    "Perwez",
    "Manizales",
    "Witten",
    "Forges-sur-Meuse",
    "Welschenrohr",
    "Berthier-sur-Mer",
    "Bukavu",
    "Neuville-sous-Montreuil",
    "Manhattan",
    "Bayonne",
    "Carnac",
    "Etterbeek",
    "Queens",
    "Beaumont",
    "Melbourne",
    "Offenbach-sur-le-Main",
    "Groix",
    "Bristol",
    "Marbella",
    "Itumbiara",
    "Séville",
    "Alicante",
    "Asuncion",
    "Lokeren",
    "Maceió",
    "Hautmont",
    "Bilbao",
    "Lérida",
    "Pereira",
    "Liège",
    "Saverne",
    "Allouagne",
    "Marvejols",
    "Clermont-Ferrand",
    "Chênée",
    "Rouyn",
    "Nauen",
    "Berlin-Wedding",
    "Klagenfurt",
    "Teplice",
    "Darłowo",
    "Kołobrzeg",
    "Jepara",
    "Gitega",
    "Bunnik",
    "Kashiwa",
    "Montana",
    "Beaconsfield",
    "Shizuoka",
    "Pétion-Ville",
    "Brockton",
    "Cobourg",
    "Sderot",
    "Wendake",
    "Wriezen",
    "Calcutta",
    "Manacor",
    "Cesena",
    "Korhogo",
    "Aalborg",
    "Udine",
    "Caen",
    "Kikwit",
    "Clamart",
    "Saint-Nazaire",
    "Cervia",
    "Raqqa",
    "Yuncheng",
    "Hořovice",
    "Alphen-sur-le-Rhin",
    "Valkenswaard",
    "Sheffield",
    "Tassin-la-Demi-Lune",
    "Narvik",
    "Québec",
    "Karlsruhe",
    "Sukabumi",
    "Valence",
    "Heilly",
    "Suze-la-Rousse",
    "Orbe",
    "La Brévine",
    "Alban",
    "Binche",
    "Rouyn-Noranda",
    "Pointe-Noire",
    "Pernes-les-Fontaines",
    "Nonville",
    "Quéven",
    "Molenbeek-Saint-Jean",
    "Senlis",
    "Frameries",
    "Vire",
    "Louvain",
    "Papeete",
    "Bois-d'Haine",
    "Saint-Amand-les-Eaux",
    "Québec",
    "Uppsala",
    "Lynden",
    "Roverbella",
    "Constantine",
    "Vaison-la-Romaine",
    "Mayenne",
    "Ratisbonne",
    "Weinberg",
    "Tübingen",
    "Pittsburgh",
    "Baie-Saint-Paul",
    "Saint-Imier",
    "Saint-Martin-de-Seignanx",
    "Piré-sur-Seiche",
    "Saumur",
    "Thessalonique",
    "Cheyres",
    "Iriba",
    "Ljubljana",
    "Corbeil-Essonnes",
    "Sulzbach-Rosenberg",
    "Sangerhausen",
    "Asnières-sur-Seine",
    "São João da Madeira",
    "Terrebonne",
    "Vierzon",
    "Arlon",
    "Jumet",
    "Pontcey",
    "Murici",
    "Valens",
    "Wieruszów",
    "Inowrocław",
    "Canelones",
    "Buenos Aires",
    "Estamira",
    "Telfes im Stubai",
    "Pont-l'Abbé",
    "Andorre-la-Vieille",
    "Sanok",
    "Göteborg",
    "Meung-sur-Loire",
    "Sherbrooke",
    "Allonville",
    "Fribourg-en-Brisgau",
    "Montluçon",
    "Londerzeel",
    "Healdsburg",
    "Jakarta",
    "Saint-Quentin",
    "Sainte-Anne-de-la-Pocatière",
    "Langolen",
    "Sant'Angelo Lodigiano",
    "Bénévent",
    "Sinaloa",
    "Cosenza",
    "Düren",
    "Vintimille",
    "Souvret",
    "Ouidah",
    "Rybany",
    "Milton",
    "Flobecq",
    "Birmingham",
    "Berlin-Est",
    "Liesek",
    "Withypool",
    "Padoue",
    "Ferrare",
    "Versailles",
    "Mazy",
    "Oucques",
    "Mostaganem",
    "Sienne",
    "Talence",
    "Calgary",
    "Toulon",
    "Chepetivka",
    "Héraklion",
    "Coinches",
    "Estaires",
    "Oujda",
    "Chabanais",
    "Hirson",
    "Avenches",
    "Béguey",
    "Roanne",
    "Genk",
    "Pančevo",
    "Bratislava",
    "Moyeuvre-Grande",
    "Munakata",
    "Hachiōji",
    "Laghouat",
    "Bizerte",
    "Gouda",
    "Baden-Baden",
    "Bergen",
    "Tiaret",
    "Ourossogui",
    "Chêne-Bougeries",
    "Verviers",
    "El Ksiba",
    "Beuvry",
    "Anápolis",
    "Riec-sur-Bélon",
    "Harrisburg",
    "Little Rock",
    "Mississauga",
    "San Salvador",
    "Dassa-Zoumè",
    "Mons",
    "Allemagne-en-Provence",
    "Niedernai",
    "Soissons",
    "Hilversum",
    "Viazma",
    "Yopougon",
    "Bangkok",
    "Opole",
    "Thunder Bay",
    "Phnom-Penh",
    "Lifou",
    "Hartola",
    "Constantinople",
    "Kharkiv",
    "Iéna",
    "Berlaimont",
    "Saint-Julien-en-Genevois",
    "Woluwe-Saint-Lambert",
    "Saint-Jean-de-Luz",
    "Ouahigouya",
    "Milev",
    "Offenbourg",
    "Bandung",
    "Catane",
    "Coblence",
    "Riga",
    "Rufisque",
    "Nantucket",
    "Ludhiana",
    "Bad Kösen",
    "Chiavenna",
    "Vendôme",
    "Loudima",
    "Ninove",
    "Louiseville",
    "Chihuahua",
    "Saint-Joseph",
    "Mantes-la-Jolie",
    "Camphin-en-Carembault",
    "Anglès",
    "Avignon",
    "Montmerle-sur-Saône",
    "Biedermannsdorf",
    "Cottbus",
    "Hachy",
    "Bohicon",
    "Asbestos",
    "Mossoul",
    "Amstetten",
    "Ivanovo",
    "Anorí",
    "Saragosse",
    "Vänersborg",
    "Wellington",
    "Portsmouth",
    "Tenterden",
    "Altenbourg",
    "Rumilly",
    "Bourg-la-Reine",
    "Loches-sur-Ource",
    "Grigny",
    "Zwolle",
    "Palerme",
    "Vipiteno",
    "Colorno",
    "Cahors",
    "Bouchemaine",
    "Guingamp",
    "Champigny-sur-Marne",
    "Queyrac",
    "Noale",
    "Joigny",
    "Hódmezővásárhely",
    "Torrelavega",
    "Wettingen",
    "Malgaches",
    "Gelsenkirchen",
    "Farmville",
    "Cuxac-Cabardès",
    "Joué-lès-Tours",
    "Fort-de-France",
    "Santiago du Chili",
    "Saint-Gall",
    "Quedlinburg",
    "Oelsnitz",
    "Innsbruck",
    "Fauquemont-sur-Gueule",
    "Ebolowa",
    "Castres",
    "Albi",
    "Marcinelle",
    "Beauvais",
    "Chambéry",
    "Aalter",
    "Ajaccio",
    "Iowa",
    "Ath",
    "Schwendi",
    "Saint-Drézéry",
    "Buffalo",
    "Tirana",
    "Milwaukee",
    "Gagnoa",
    "Ostrava",
    "Moudon",
    "Tacaná",
    "Martigny",
    "Bex",
    "Provins",
    "Saint-Jorioz",
    "Nuremberg",
    "Sotchi",
    "Tarragone",
    "Porto",
    "Réghaïa",
    "Labé",
    "Foumban",
    "Bougainville",
    "Praia",
    "Ushuaïa",
    "Kengtung",
    "Cleveland",
    "Salquenen",
    "Aveiro",
    "Puttaparthi",
    "Višegrad",
    "Koszalin",
    "Xalapa",
    "Hopa",
    "Pristina",
    "Saitama",
    "Kankan",
    "Dielsdorf",
    "Kehra",
    "Diegem",
    "Bratsigovo",
    "Duffel",
    "Tbilissi",
    "Port-Gentil",
    "Kikinda",
    "Zehdenick",
    "Talkeetna",
    "Trondheim",
    "Mechhed",
    "Vanves",
    "Kiev",
    "Lisieux",
    "Asti",
    "Elbląg",
    "Rzeszów",
    "Abéché",
    "Vancouver",
    "Hobart",
    "Agadir",
    "Les Cayes",
    "Cowansville",
    "Virton",
    "Linköping",
    "Seclin",
    "Marconne",
    "Hemmingstedt",
    "Odense",
    "Stratford",
    "Rowley",
    "Greystones",
    "Roskilde",
    "Logroño",
    "Beaugency",
    "Randers",
    "Tokyo",
    "Oulan-Bator",
    "Salerne",
    "Lucerne",
    "Oaxaca",
    "Wattwil",
    "Kaysersberg",
    "La Possession",
    "Rawalpindi",
    "Khartsyzk",
    "Zgierz",
    "Esch-sur-Alzette",
    "Kragujevac",
    "Aire-sur-l'Adour",
    "Granges-près-Marnand",
    "Oneglia",
    "Brie-Comte-Robert",
    "Tchibanga",
    "Schleusingen",
    "Oldenbourg",
    "Seligenstadt",
    "Karachi",
    "Shantou",
    "Jacareí",
    "Barth",
    "Duisbourg",
    "Głogów",
    "Neufelden",
    "Youngstown",
    "Höxter",
    "Bressanone",
    "Osterwieck",
    "Hulan",
    "Silvan",
    "Calakmul",
    "Saint-Martin-de-Ré",
    "Saint-Chamond",
    "Chenu",
    "Perros-Guirec",
    "Pont-à-Mousson",
    "Dinant",
    "Monceau-sur-Sambre",
    "Moûtiers",
    "N'Djaména",
    "Hama",
    "Kandi",
    "Pécs",
    "Pforzheim",
    "Ferrol",
    "Bourbon-Lancy",
    "Monteux",
    "Saint-Laurent-de-la-Salanque",
    "Mirecourt",
    "Auberchicourt",
    "Bafia",
    "Boulogne-sur-Mer",
    "Lambézellec",
    "Differdange",
    "Saint-Affrique",
    "Amagne",
    "Suippes",
    "Litomyšl",
    "Caranceja",
    "Hildesheim",
    "Norroy-lès-Pont-à-Mousson",
    "Remiremont",
    "Pretoria",
    "Portalbera",
    "Gozo",
    "Vilosnes",
    "Manchester",
    "Béguédo",
    "Minden",
    "Cruseilles",
    "Bassorah",
    "Saint-Malo",
    "Valdegeña",
    "Étroussat",
    "Fermo",
    "L'Aquila",
    "Malgrate",
    "Calais",
    "Tréméoc",
    "Minsk",
    "Brestot",
    "Stockwell",
    "Troyes",
    "Trieste",
    "Argentan",
    "Vientiane",
    "Città di Castello",
    "Évora",
    "Pise",
    "Thonne-le-Thil",
    "Bonaléa",
    "Bellac",
    "Malmedy",
    "Wettolsheim",
    "Carpentras",
    "Mesnil-Saint-Georges",
    "Marnham",
    "Épernay",
    "Putot-en-Auge",
    "Watsonville",
    "Guanghan",
    "Coudures",
    "Sparte",
    "Braga",
    "Langres",
    "Châlons-sur-Marne",
    "Le Caire",
    "Steenwijkerland",
    "Gonesse",
    "Viviez",
    "Cagliari",
    "Auneuil",
    "Boqueho",
    "Gueugnon",
    "Lobbes",
    "Derbyhaven",
    "Mayrac",
    "Riva Valdobbia",
    "Calanda",
    "Kidal",
    "Châlons-en-Champagne",
    "Pézenas",
    "Morlaix",
    "Isle-Saint-Georges",
    "Vannes",
    "Lomé",
    "Bafoussam",
    "Maniwaki",
    "Radstadt",
    "Conflans-Sainte-Honorine",
    "Eboli",
    "Palafrugell",
    "Chalon-sur-Saône",
    "Kairouan",
    "Ilonse",
    "Damas",
    "Tønder",
    "Zerbst",
    "Lindau",
    "Uffholtz",
    "Flessingue",
    "Alexandrie",
]

NORTHERN_EUROPE = [
    "Angleterre",
    "Danemark",
    "Estonie",
    "Écosse",
    "Finlande",
    "Irlande",
    "Irlande du Nord",
    "Islande",
    "Lettonie",
    "Lituanie",
    "Norvège",
    "Pays de Galles",
    "Royaume-Uni",
    "Suède",
]

WESTERN_EUROPE = [
    "Allemagne",
    "Andorre",
    "Autriche",
    "Belgique",
    "France",
    "Liechtenstein",
    "Luxembourg",
    "Monaco",
    "Pays-Bas",
    "Suisse",
]

SOUTHERN_EUROPE = [
    "Albanie",
    "Bosnie-Herzégovine",
    "Chypre",
    "Chypre du Nord",
    "Croatie",
    "Espagne",
    "Grèce",
    "Italie",
    "Kosovo",
    "Macédoine",
    "Macédoine du Nord",
    "Malte",
    "Monténégro",
    "Portugal",
    "Saint-Marin",
    "Serbie",
    "Slovénie",
    "Vatican",
]

EASTERN_EUROPE = [
    "Biélorussie",
    "Moldavie",
    "Pologne",
    "République tchèque",
    "Roumanie",
    "Slovaquie",
    "Ukraine",
    "Russie",
]

NORTH_AFRICA = [
    "Algérie",
    "Égypte",
    "Libye",
    "Maroc",
    "Soudan",
    "Tunisie",
]

WEST_AFRICA = [
    "Bénin",
    "Burkina Faso",
    "Cap-Vert",
    "Côte d'Ivoire",
    "Gambie",
    "Ghana",
    "Guinée",
    "Guinée-Bissau",
    "Liberia",
    "Mali",
    "Mauritanie",
    "Niger",
    "Nigeria",
    "Sénégal",
    "Sierra Leone",
    "Togo",
]

CENTRAL_AFRICA = [
    "Angola",
    "Burundi",
    "Cameroun",
    "République centrafricaine",
    "République du Congo",
    "République démocratique du Congo",
    "Gabon",
    "Guinée équatoriale",
    "Rwanda",
    "São Tomé-et-Principe",
    "Tchad",
]

EAST_AFRICA = [
    "Comores",
    "Djibouti",
    "Érythrée",
    "Éthiopie",
    "Kenya",
    "Madagascar",
    "Malawi",
    "Maurice",
    "Mozambique",
    "Ouganda",
    "Seychelles",
    "Somalie",
    "Soudan du Sud",
    "Tanzanie",
    "Zambie",
    "Zimbabwe",
]

SOUTHERN_AFRICA = [
    "Afrique du Sud",
    "Botswana",
    "Eswatini",
    "Lesotho",
    "Namibie",
]

MIDDLE_EAST = [
    "Arabie saoudite",
    "Bahreïn",
    "Émirats arabes unis",
    "Irak",
    "Iran",
    "Israël",
    "Jordanie",
    "Koweït",
    "Liban",
    "Oman",
    "Palestine",
    "Qatar",
    "Syrie",
    "Turquie",
    "Yémen",
]

CENTRAL_ASIA = [
    "Afghanistan",
    "Kazakhstan",
    "Kirghizistan",
    "Ouzbékistan",
    "Tadjikistan",
    "Turkménistan",
]

EAST_ASIA = [
    "Chine",
    "Corée du Nord",
    "Corée du Sud",
    "Japon",
    "Mongolie",
    "Taïwan",
    "Taiwan"
]

SOUTH_ASIA = [
    "Bangladesh",
    "Bhoutan",
    "Inde",
    "Maldives",
    "Népal",
    "Pakistan",
    "Sri Lanka",
]

SOUTHEAST_ASIA = [
    "Birmanie",
    "Brunei",
    "Cambodge",
    "Indonésie",
    "Laos",
    "Malaisie",
    "Philippines",
    "Singapour",
    "Thaïlande",
    "Timor oriental",
    "Viêt Nam",
]

CAUCASUS = [
    "Abkhazie",
    "Arménie",
    "Azerbaïdjan",
    "Géorgie",
    "Ossétie du Sud-Alanie",
]

ANGLO_AMERICA = [
    "Canada",
    "États-Unis",
]

CENTRAL_AMERICA = [
    "Belize",
    "Costa Rica",
    "Guatemala",
    "Honduras",
    "Mexique",
    "Nicaragua",
    "Panama",
    "Salvador",
]

CARIBBEAN = [
    "Antigua-et-Barbuda",
    "Bahamas",
    "Barbade",
    "Cuba",
    "Dominique",
    "Grenade",
    "Haïti",
    "Jamaïque",
    "République dominicaine",
    "Saint-Christophe-et-Niévès",
    "Sainte-Lucie",
    "Saint-Vincent-et-les Grenadines",
    "Trinité-et-Tobago",
]

SOUTH_AMERICA = [
    "Argentine",
    "Bolivie",
    "Brésil",
    "Chili",
    "Colombie",
    "Équateur",
    "Guyana",
    "Paraguay",
    "Pérou",
    "Suriname",
    "Uruguay",
    "Venezuela",
]

AUSTRALASIA = [
    "Australie",
    "Nouvelle-Zélande",
]

MELANESIA = [
    "Fidji",
    "Papouasie-Nouvelle-Guinée",
    "Îles Salomon",
    "Vanuatu",
]

MICRONESIA = [
    "Kiribati",
    "Îles Marshall",
    "Micronésie",
    "Nauru",
    "Palaos",
]

POLYNESIA = [
    "Îles Cook",
    "Niue",
    "Samoa",
    "Tonga",
    "Tuvalu",
]

LIST_OF_REGIONS = [
    NORTHERN_EUROPE,
    WESTERN_EUROPE,
    SOUTHERN_EUROPE,
    EASTERN_EUROPE,
    NORTH_AFRICA,
    WEST_AFRICA,
    CENTRAL_AFRICA,
    EAST_AFRICA,
    SOUTHERN_AFRICA,
    MIDDLE_EAST,
    CENTRAL_ASIA,
    EAST_ASIA,
    SOUTH_ASIA,
    SOUTHEAST_ASIA,
    CAUCASUS,
    ANGLO_AMERICA,
    CENTRAL_AMERICA,
    CARIBBEAN,
    SOUTH_AMERICA,
    AUSTRALASIA,
    MELANESIA,
    MICRONESIA,
    POLYNESIA,
]


MINIMAL_PRECISSENES_SCORE: int = 650
LIST_OF_REAL_PEOPLE_FILEPATH: str = "list_of_wikipedia_page_of_real_people.txt"

HISTORICAL_PERIODS = [
    "Prehistory",
    "Antiquity",
    "Middle Ages",
    "Renaissance",
    "Contemporary Period",
    "Today Time"
]

HISTORICAL_PERIODS_TIME = [
    "-99999"
    "-3300",
    "476",
    "1492",
    "1789",
    "2000"
]

JOBS_PREFIX = [
    # Chefs d'État et de gouvernement
    "chef",
    "Dirigeant de facto",
    "Dirigeant de facto de",
    "Dirigeant de facto des",
    "Dirigeant de facto du",
    "Dirigeant de facto d'",
    "Dirigeant du",
    "Dirigeant de",
    "Dirigeant des",
    "Dirigeant d'",
    "Dirigeante du",
    "Dirigeante de",
    "Dirigeante des",
    "Dirigeante d'",
    
            
    "Roi d'Angleterre et d'"
    "Reine d'",
    "Reine des",
    "Reine du",
    "Reine de"
    "Dirigeante de facto de",
    "Dirigeante de facto des",
    "Dirigeante de facto du",
    "Dirigeante de facto d'",
    "Première dame d'",
    "Première dame du",
    "Première dame de",
    "Première dame des",
    "secrétaire du comité exécutif",
    "secrétaire général",
    "Lord-protecteur du",
    "Lord-protecteur d'",
    "Lord-protecteur des",
    "Lord-protecteur de",
    "secrétaire général du ",
    "secrétaire général des",
    "premier secrétaire du",
    "premier secrétaire des",
    "premier secrétaire de",
    "premier secrétaire d'",
    "premiere secrétaire du",
    "premiere secrétaire des",
    "premiere secrétaire de",
    "premiere secrétaire d'",
    "Chef suprême de la",
    "Chef suprême du",
    "Chef suprême des",
    "Chef suprême d'",
    "Cheffe suprême de la",
    "Cheffe suprême du",
    "Cheffe suprême des",
    "Cheffe suprême d'"
    "chef de",
    "chef d'",
    "chef d'État",
    "chef de gouvernement",
    "chef de l'État",
    "chef de l'opposition",
    "reine du royaume-Uni et des",
    "roi du royaume-Uni et des",
    "président",
    "président du",
    "président des",
    "président de",
    "président d'",
    "président élu",
    "président-directeur général",
    "président directeur général",

    "vice-président",
    "vice-président de",
    "vice-président d'",

    "premier ministre",
    "vice-premier ministre",
    "ministre en chef",
    "chancelier",
    "vice-chancelier",
    "directeur général du"
    "directeur général des"
    "directeur général d'"

    # Ministres
    "ministre",
    "ministre de",
    "ministre d'",
    "ministre des",
    "ministre du",
    "ministre de la",
    "ministre de l'",
    "ministre d'État",
    "ministre délégué",
    "secrétaire d'État",

    "ministre des affaires étrangères",
    "ministre de l'intérieur",
    "ministre de la défense",
    "ministre de l'éducation",
    "ministre de la justice",
    "ministre des finances",
    "ministre de la santé",
    "ministre de l'économie",
    "ministre du travail",
    "ministre des transports",
    "ministre de l'agriculture",
    "ministre du développement",
    "ministre du développement national",
    "ministre du développement national et rural",
    "ministre de la culture",
    "ministre de l'environnement",

    # Parlement
    "député",
    "député à la chambre des représentants",
    "député européen",
    "sénateur",
    "parlementaire",
    "Député du",
    "Député de la",
    "Députée de la",
    "Député des",
    "Député de",
    "Député de l'",
    "Députée du",
    "Députée des",
    "Députée de",
    "Députée de l'",
    "Député au",
    "Députée au",
    # Sénateur

    "Sénateur du",
    "Sénateur des",
    "Sénateur de",
    "Sénateur de l'",
    "Sénatrice du",
    "Sénatrice des",
    "Sénatrice de",
    "Sénatrice de l'",

    # Parlementaire

    "Parlementaire du",
    "Parlementaire des",
    "Parlementaire de",
    "Parlementaire de l'",
    "membre du",
    "membres des",
    "membre de",
    "membre d'"
    "membre du parlement",
    "membre de la chambre des représentants",

    # Exécutif territorial
    "gouverneur",
    "gouverneur de",
    "gouverneur d'",
    "gouverneur général",
    "vice-gouverneur",
    "maire",
    "adjoint au maire",
    "préfet",
    "sous-préfet",

    # Diplomatie
    "ambassadeur",
    "haut-commissaire",
    "commissaire",
    "consul",
    "consul général",
    "représentant permanent",
    "représentant de",
    "représentant d'",
    "envoyé spécial",

    # Administration
    "administrateur",
    "administrateur général",

    "directeur",
    "directeur de",
    "directeur d'",
    "directeur général",
    "directeur général de",
    "directeur exécutif",
    "directeur adjoint",
    "directeur de cabinet",

    "chef de cabinet",

    "secrétaire de",
    "secrétaire d'",
    "secrétaire général",
    "secrétaire général de",
    "secrétaire général de l'"
    "secrétaire exécutif",
    "secrétaire général du",
    "secrétaire général des",
    "coordonnateur",
    "inspecteur",
    "contrôleur",
    "trésorier",

    # Armée
    "général",
    "général de brigade",
    "général de division",
    "général d'armée",
    "maréchal",
    "colonel",
    "lieutenant-colonel",
    "major",
    "capitaine",
    "commandant",
    "commandant de",
    "commandant d'",
    "commandant en chef",
    "chef d'état-major",

    # Justice
    "juge",
    "magistrat",
    "procureur",
    "procureur général",
    "avocat général",
    "avocat",
    "notaire",
    "greffier",
    "juriste",
    "conseiller juridique",
    "Vice-président de l'",
    "Vice-président des l'",
    "Vice-président du l'",
    "Vice-président de ",
    "Vice-président du",
    "Vice-président des'",
    "Vice-présidente de l'",
    "Vice-présidente des l'",
    "Vice-présidente du l'",
    "Vice-présidente de ",
    "Vice-présidente du",
    "Vice-présidente des'",
    "Président général du",
    "Président général des",
    "Président général de",
    "Président général du l'",
    "Président général des l'",
    "Président général de l'",
    "Présidente général du",
    "Présidente général des",
    "Présidente général de",
    "Présidente général du l'",
    "Présidente général des l'",
    "Présidente général de l'",
        
        
    # Université
    "professeur",
    "enseignant",
    "chercheur",
    "recteur",
    "doyen",
    "universitaire",
    "Directeur de l'",
    "Directrice de l'"

    # Économie
    "économiste",
    "entrepreneur",
    "homme d'affaires",
    "banquier",
    "financier",
    "industriel",
    "commerçant",

    # Sport
    "président de la",
    "présidente de la",
        
    "président de la fédération",
    "président de l'association",
    "président de l'",
    "présidente de l",
    "président de club",
    "entraîneur",
    "sélectionneur",
    "arbitre",
    "dirigeant sportif",
    "administrateur de football",

    # Religion
    "évêque",
    "archevêque",
    "cardinal",
    "imam",
    "pasteur",
    "rabbin",
    "moine",

    # Noblesse
    "roi",
    "reine",
    "empereur",
    "impératrice",
    "prince",
    "princesse",
    "sultan",

    # Divers
    "conseiller",
    "conseiller de",
    "conseiller d'",
    "conseiller municipal",
    "conseiller régional",
    "conseiller présidentiel",
    "porte-parole",
    "fonctionnaire",
    "haut fonctionnaire",
    "militant",
    "activiste",
    "syndicaliste",
    "journaliste",
    "écrivain",
    "médecin",
    "ingénieur",
    "chef de guerre",
    "chef rebelle",
    "chef traditionnel",
    "cheffe",
    "chef de l'"
    "cheffe de",
    "cheffe d'",

    "présidente",
    "présidente de",
    "présidente du",
    "présidente des",        
    "présidente d'",
    "vice-présidente",
    "vice-présidente de",
    "vice-présidente d'",

    "première ministre",
    "vice-première ministre",
    "ministre",  # identique au masculin
    "ministre en chef",
    "ministre déléguée",
    "secrétaire d'État",  # identique
    "secrétaire générale",
    "secrétaire générale de",
    "secrétaire exécutive",

    "députée",
    "sénatrice",
    "parlementaire",
    "führer du",
    "gouverneure",
    "vice-gouverneure",
    "gouverneure générale",

    "mairesse",
    "maire",  # certains pays utilisent toujours "maire"
    "adjointe au maire",

    "préfète",
    "sous-préfète",

    "ambassadrice",
    "haute-commissaire",
    "commissaire",  # identique
    "consule",
    "consule générale",
    "représentante permanente",
    "représentante de",
    "représentante d'",
    "envoyée spéciale",

    "administratrice",
    "administratrice générale",

    "directrice",
    "directrice de",
    "directrice d'",
    "directrice générale",
    "directrice générale de",
    "directrice générale du",
    "directrice générale des",
    "directrice générale '",
    "directrice exécutive",
    "directrice adjointe",
    "directrice de cabinet",

    "cheffe de cabinet",

    "coordinatrice",
    "inspectrice",
    "contrôleuse",
    "trésorière",

    "générale",
    "générale de brigade",
    "générale de division",
    "générale d'armée",

    "commandante",
    "commandante de",
    "commandante d'",
    "commandante en chef",

    "juge",  # identique
    "magistrate",
    "procureure",
    "procureure générale",
    "avocate générale",
    "avocate",
    "notaire",  # souvent identique
    "greffière",
    "juriste",  # identique
    "conseillère juridique",

    "professeure",
    "enseignante",
    "chercheuse",
    "rectrice",
    "doyenne",
    "universitaire",

    "économiste",  # identique
    "entrepreneuse",
    "femme d'affaires",
    "banquière",
    "financière",
    "industrielle",
    "commerçante",

    "présidente de la fédération",
    "présidente de l'association",
    "présidente de club",
    "entraîneuse",
    "sélectionneuse",
    "arbitre",  # identique
    "dirigeante sportive",
    "administratrice de football",

    "évêque",  # identique
    "pasteure",
    "rabbin",  # généralement identique
    "religieuse",

    "reine",
    "impératrice",
    "princesse",
    "sultane",

    "conseillère",
    "conseillère de",
    "conseillère d'",
    "conseillère municipale",
    "conseillère régionale",
    "conseillère présidentielle",

    "porte-parole",  # identique
    "fonctionnaire",  # identique
    "haute fonctionnaire",

    "militante",
    "activiste",  # souvent identique
    "syndicaliste",  # identique
    "journaliste",  # identique
    "écrivaine",
    "autrice",
    "auteure",
    "médecin",  # identique
    "ingénieure",

    "cheffe de guerre",
    "cheffe rebelle",
    "cheffe traditionnelle",
    "chercheur en",
    "chercheuse en",  
    "rédactrice à",
    "rédactrice chez",
    "chef d'état major des forces",
    "Président délégué du",
    "Président délégué des",
    "Président délégué de",
    "Président délégué d'",
    "Présidente délégué du",
    "Présidente délégué des",
    "Présidente délégué de",
    "Présidente délégué d'",
        
    
]


LIST_OF_INCOMPLETE_JOB = [
    "Y'en a marre (mouvement)",
    "Université Paris-VIII-Vincennes-Saint-Denis",
    "Parti progressiste-conservateur du Canada",
    "Résistance (politique)",
    "Généralité de Catalogne",
    "Prix du Maroc du livre",
    "Liste des présidents du Raja Club Athletic",
    "Préfecture de Casablanca",
    "Union marocaine pour la démocratie",
    "Gouvernement Bouabid II",
    "Technologies de l'information et de la communication pour l'enseignement",
    "Union constitutionnelle",
    "Résistance (politique)",
    "Circonscription de Tozeur",
    "Assemblée nationale constituante",
    "Front de libération nationale (Algérie)",
    "Armée de la république islamique d'Iran",
    "Y'en a marre (mouvement)",
    "West Haven (Connecticut)",
    "Union économique et monétaire ouest-africaine",
    "Parlement de la région de Bruxelles-Capitale",
    "Organisation nationale des Malais unis",
    "Armée de terre bangladaise",
    "Service national de la Sécurité",
    "Coutances et Avranches",
    "Résistance intérieure française",
    "Comptabilité d'entreprise",
    "Ministère (christianisme)",
    "Brigades Izz al-Din al-Qassam",
    "Pâturage (alimentation)",
    "Abu Yusuf Yaqub ben Abd al-Haqq",
    "Commandant (homonymie)",
    "Patinage de vitesse sur piste courte",
    "Assemblée législative du Québec",
    "Congrégation pour les Églises orientales",
    "Centre national de la recherche scientifique",
    "Saint-Méloir-des-Bois",
    "Liste alphabétique des pilotes de rallye",
    "Chambre des représentants",
    "L'Engrenage (film, 1998)",
    "Ordre de Saint-Benoît",
    "Ducs puis princes lombards de Bénévent",
    "Saison 2018-2019 de la LHOu",
    "Position (hockey sur glace)",
    "Assemblée législative de la Colombie-Britannique",
    "1445 en musique classique",
    "Gymnastique rythmique",
    "Parti national fasciste",
    "Brava (municipalité du Cap-Vert)",
    "Parti Communiste de Belgique",
    "Orientalisme (études orientales)",
    "Liste d'as de l'aviation",
    "Chemin de fer de la Jungfrau",
    "Grand Hotel (film, 1932)",
    "Vendredi 13 (film, 1980)",
    "Banshee (série télévisée)",
    "Le Juif Süss (film, 1940)",
    "Faut s'les faire... ces légionnaires !",
    "Hockey sur glace en 1999",
    "ALO docView - Lexikon deutscher Frauen der Feder. Eine Zusammenstellung der seit dem Jahre 1840 erschienenen Werke weiblicher Autoren, nebst",
    "Atlantic City (New Jersey)",
    "Beauvais, Noyon et Senlis",
    "Saint-Jacques-de-Compostelle",
    "Cimetière de l'Est (Boulogne-sur-Mer)",
    "Rodolphe de Rheinfelden",
    "Pierre Legardeur de Repentigny",
    "Guillaume de Nassau-Dillenbourg",
    "Emmanuel Richard Priso Ngom Priso",
    "De Nouvelle-Aquitaine",
    "Conseil constitutionnel",
    "D'agglomération Amiens Métropole",
    "de la Jeunesse d'Allemagne",
    "La Danseuse nue (film, 1952)",
    "Illusions (film, 1930)",
    "Le Portrait de Dorian Grey (film, 1915)",
    "Mare Nostrum (film, 1926)",
    "Viktor und Viktoria (film, 1933)",
    "L'amour ne meurt jamais",
    "2023 en hockey sur glace",
    "1998 en hockey sur glace",
    "Hockey sur glace en 2006",
    "Hockey sur glace en 1999",
    "Hockey sur glace en 1987",
    "Hockey sur glace en 1977",
    "Hockey sur glace en 1971",
    "Première guerre intercoloniale",
    "Siège de Lilybée (250 av. J.-C.-241 av. J.-C.)",
    "Www.pietro-lombardi.com",
    "Www.pieroesteriore.com",
    "For the majority of the congress members, the only essential difference between a republic and the",
    "Activités principales exercées",
    "Arrière-arrière-petit-fils",
    "Jacqueline Scott-Lemoine",
    "Marcus Fulvius Curvus Paetinus",
    "Jean Doukas Kamatéros",
    "Cosmo Edmund Duff Gordon",
    "Joseph (Nouveau Testament)",
    "Joseph Jacques Marest",
    "William Cubitt (1785-1861)",
    "Pierre-Antoine Demachy",
    "Philippe Lacoue-Labarthe",
    "Louis-Gabriel Michaud",
    "François Gracchus Cabrol",
    "Amédée Renault-Morlière",
    "Nelly Marandon de Montyel",
    "Giovanni Francesco Cassana",
    "Karl Friedrich Schinkel",
    "Heinrich Dietrich von Grolman",
    "David Thompson (homme politique canadien)",
    "Henry Oakes (général)",
    "Lucien Boyer (chansonnier)",
    "Susan Thornton Glassell",
    "Liste d'écrivains de langue française par ordre alphabétique",
    "Les Bas-fonds (Gorki)",
    "Gironde (département)",
    "Liste de militants écologistes",
    "Dynastie hachémite",
    "Lucius",
    "Syrie",
    "Poésie",
    "dés",
    "Descendant",
    "Théâtre",
    "Galilée",
    "des"

]


HTML_ELEMENT_LIST = [
    "<a href=",
    "</a>",
    "</div>",
    "<div class=",
    "</td>",
    "<td>",
    "</th>",
    "<th>",
    "<tr>",
    "</tr>",
    "<tbody>",
    "</tbody>",
    "<table>",
    "</table>",
    "<caption>",
    "</caption>",
    "<span class=",
    "</span>",
    "<sup>",
    "</sup>",
    "<small>",
    "</small>",
    "<p>",
    "</p>",
    "<ul>",
    "</ul>",
    "<li>",
    "</li>",
    "<i>",
    "</i>",
    "<b>",
    "</b>",
    "<br>",
    "<br/>",
    "<time class=",
    "<time datetime=",
    "<abbr class=",
    "<meta name=",
    "<title>",

    # Attributs HTML
    "class=",
    "id=",
    "scope=",
    "colspan=",
    "rowspan=",
    "style=",
    "href=",
    "src=",
    "datetime=",
    "data-sort-value=",
    "data-sort-type=",
    "rel=",

    # Classes / fragments CSS
    "mw-redirect",
    "mw-disambig",
    "cite-bracket",
    "reference",
    # "nowrap",
    # "external",
    # "extiw",
    "skin-theme-clientpref-day",
    "vector-feature-main-menu-pinned-disabled",
    "vector-feature-limited-width-clientpref-1",
    "vector-feature-limited-width-content-enabled",
    "vector-feature-custom-font-size-clientpref-1",
    "vector-feature-appearance-pinned-clientpref-0",
    "vector-sticky-header-enabled",

    # Références Wikipédia
    "#cite note-",
    "#cite ref-",
    "cite note-",
    "cite ref-",
    "Styles:r",
    "BNF",
    "International Standard Book Number",
    "https://www.wikidata.org/",
    "https://en.wikipedia.org/",

    # Morceaux de code HTML
    "</th><td",
    "<td colspan=",
    "<th scope=",
    "<tr class=",
    "<tbody><tr",
    "<span data-sort-value=",
    "<abbr class=",
    "<time class=",
    # Non html elem
    " Décès ",
    "Décès ",
    "Liste des",
    "années 1",
    "années 2",
    "années 3",
    "années 4",
    "années 5",
    "années 6",
    "années 7",
    "années 8",
    "années 9",
            
        

]
NON_TOWN_ELEMENT_LIST = [
    # Balises HTML
    # Valeurs parasites
    ",",
    "(",
    ")",
    "?",
    "-",
    "–",
    "...",
    "p.",
    "pp.",
    "m",
    "le",
    "la",
    "de",
    "des",
    "du",
    "à",
    "ou",
    "et",
    "mais",
    "contre",
    "près",
    "au",
    "dans",
    "[",
    "]",
    "Données",
    # Catégories / métadonnées Wikipédia
    "Biographie",
    "Décès",
    "Naissance",
    "Nationalité",
    "Religion",
    "Genre",
    "Voix",
    "Labels",
    "Activité",
    "Activités",
    "Fonction",
    "Fonctions",
    "Titre",
    "Lieu",
    "Poste",
    "Prédécesseur",
    "Successeur",
    "Famille",
    "Dynastie",
    "Époque",
    "Ordination",
    "Sépulture",
    "Autre titre",
    "Autres titres",
    "Hôtel de la reine Hortense",
    "Symphonie",
    "Ville libre d'Empire",
    "Vindex",
    "Lichtental,",
    "par",
    "Gia",
    "Rue Saint-Denis",
    "Hôtel de Condé",
    "mars",
    "France",
    "Inde",
    "Touraine",
    "Antonin le Pieux",
    "Enseignement",
    "Rue de Clichy",
    "Pays-Bas",
    ")",
    "(7",
    "Période Comnène Précédé par Nicéphore III Botaniatès Co-empereur Constantin Doukas (1074-1078 / 1081-1087",
    "Dictionnaire biographique",
    "(à",
    "6e",
    "septembre",
    "New",
    "Plutarque",
    "Nationalité",
    "(~72",
    "George Packer",
    "Bataille d'Asculum",
    "Hypace",
    "4e",
    "Antonins",
    "Égypte antique",
    "Ashfield",
    "et",
    "Rue Saint-Honoré",
    "Château",
    "Monts Khentii",
    "Paroisse",
    "Hôtel Saint-Pol",
    "août",
    "Consul",
    "Cappadoce",
    "Hürth-Hermülheim",
    "[",
    "9e",
    "13e",
    "mai",
    "alive",
    "autre",
    "Rue Saint-Denis (Paris)",
    "Ivoire",
    "15e",
    "Flavius",
    "Royaume de France",
    "condita",
    "Julio-Claudiens",
    "Dauphin",
    "Rue de la Charbonnière",
    "à",
    "Macrin",
    "Calendrier julien",
    "West",
    "Saint-Léger-de-Foucheret",
    "Lorette",
    "Mon",
    "El",
    "Riese",
    "Yahdun-Lim",
    "17e",
    "Chase",
    "c.",
    "Comté",
    "Décès",
    "Palais",
    "Constantiniens",
    "Rue du Faubourg-Poissonnière",
    "danubiennes",
    "avril",
    "Bataille de Pavie",
    "À",
    "Lucius Antonius Saturninus",
    "Asie",
    "Jean",
    "décembre",
    "Château du Stuyvenberg",
    "Dictateur",
    "Nationalité Américaine Décès 27 avril 1961 (à 67 ans",
    "Grabtown (Caroline du Nord)",
    "Nine",
    "Atar",
    "Horfield",
    "nouvelle",
    "Obergossen,",
    "Suède",
    "Liste des empereurs byzantins",
    "Dynastie thrace",
    "-450",
    "South Side (Chicago)",
    "Territoire",
    "Nom dans la langue maternelle Marcus Porcius Cato",
    "Ancien",
    "octobre",
    "Liste des rois du Wessex",
    "Italie",
    "Olympios",
    "Constantin V",
    "L'Ermitage",
    "3e",
    "Île",
    "Klein Flottbek",
    "ou",
    "Artabasde",
    "Isaurie",
    "Période Macédonienne Précédé par Zoé Porphyrogénète Michel V Co-empereur Zoé Porphyrogénète (1028-1050",
    "novembre",
    "La",
    "Liste des comtesses de Champagne",
    "Paphlagonie",
    "Australie",
    "Austrasie",
    "Fife (Écosse)",
    "Castello",
    "San",
    "un",
    "Isaac II Ange",
    "Trajan",
    "Store",
    "Barcola",
    "Château de Copenhague",
    "Liste des comtes et ducs de Savoie",
    "Jean IV Lascaris",
    "juillet",
    ",",
    "Ramaputta",
    "Romain II",
    "George",
    "Nijni",
    "Raïon",
    "Sin-muballit",
    "Basile II",
    ", initial-scale=1.0",
    "Royaume de Sicile",
    "Élimée",
    "[ 1 ]",
    "Justinien II",
    "Buda (ville)",
    "Selichtchi",
    "Anne Ange",
    "Guerre des Deux-Roses",
    "Période Lascaris Précédé par Jean III Doukas Vatatzès Suivi de Jean IV Lascaris Biographie Naissance décembre 1221 /début 1222 Nicée ( empire de Nicée",
    "Karevo",
    "février",
    "Espagne",
    "Liste des comtes de Troyes",
    "(lieu",
    "Élisabeth",
    "Rue Ambroise-Paré",
    "Saint-Empire romain germanique",
    "Jean de Joinville",
    "Buenos",
    "Colonie de la rivière Rouge",
    "Saint-Hippolyte",
    "Hoàng Trù",
    "Empire byzantin",
    "Astronomie",
    "Rhodésie du Sud",
    "Neuwaldegg",
    "Annequin",
    "Nationalité Britannique Décès 24 avril 1956 (à 85 ans",
    "Liste des ducs de Lorraine",
    "janvier",
    "Constance de Bretagne",
    "Hurstville",
    "historien",
    "Rue du Faubourg-Saint-Martin",
    "Latium",
    "Hugues IV de Bourgogne",
    "Amandus",
    "Haut-Empire romain",
    "Geoffroy II de Bretagne",
    "Spitalfields",
    "Manickpur",
    "Bury",
    "Julius Sabinus",
    "Beornred",
    "Sunrise",
    "Près",
    "Liste des comtesses et duchesses d'Anjou",
    "Michel III",
    "pont",
    "Rue Mouton-Duvernet",
    "Duché de Normandie",
    "Château de Genève",
    "Base",
    "Tavistock",
    "Norvège",
    "Staurakios",
    "Guillaume IV de Hesse-Cassel",
    "Maison de Bourbon",
    "16e",
    "Parafianovo",
    "Kensington",
    "Thibaud l'Ancien",
    "Perse",
    "av. J.-C.",
    "Boulevard de Port-Royal",
    "Astor",
    "Province du Qwara",
    "Michel II l'Amorien",
    "Petrolia",
    "Michel IV le Paphlagonien",
    "Pyrohiv",
    "Thierry Ier",
    "Hôtel",
    "Taron",
    "Période Doukas Précédé par Michel VII Doukas Usurpé par Nicéphore Basilakios Nicéphore Mélissène Suivi de Alexis I er Comnène Biographie Naissance vers 1001 Décès 10 décembre",
    "Pokrovskoïe ( Empire russe",
    "Hongrie",
    "Indochine française",
    "-",
    "Conrad de Montferrat",
    "18e",
    "Valentinien Ier",
    "Croydon",
    "Liste des seigneurs de Roannais",
    "Wessex",
    "Springwells",
    "Lead",
    "Maurice",
    "Arrondissement de Man'gyŏngdae",
    "Rome antique",
    "Hong Kong (colonie)",
    "Stone",
    "Huire,",
    "Battle Picture Weekly",
    "Cameron",
    "Karang",
    "Guerre des Despenser",
    "dans",
    "Malte",
    "Quai du Louvre",
    "Chalfont",
    "Julia Caesaris Maior",
    "Ogidi",
    "en",
    "]",
    "Liste des comtes palatins de Bourgogne",
    "Lucius Aurelius Cotta",
    "Morée",
    "Royaume de Valence",
    "Cilicie",
    "Tamayy",
    "Munsieville",
    "Duché de Clèves",
    "Domitien",
    "Fort",
    "Maison de Lusignan",
    "Gambie",
    "Mathilde d'Auvergne",
    "Zhejiang",
    "Rue de l'Arcade (Paris)",
    "Aurelia Cotta",
    "Royaume de Naples",
    "Jean sans Peur",
    "Hugues X de Lusignan",
    "Bosco",
    "Salt",
    "Guillaume II de Craon",
    "Terentius Maximus",
    "Jean",
    "Athanagilde Ier",
    "Cölln",
    "paroisses",
    "Sassanides",
    "Tunisie",
    "Lucius Cornelius Cinna",
    "Guillaume V de Nevers",
    "Henri Ier de Champagne",
    "Caecilii",
    "Iaroslav le Sage",
    "Pedro Manrique de Lara",
    "8e",
    "Molay",
    "succession",
    "Période Macédonienne Précédé par Zoé Porphyrogénète Romain III Argyre Co-empereur Zoé Porphyrogénète (1028-1050",
    "Alden",
    "of=",
    "Sant'Andrea di Barbarana",
    "Palais-musée de Tsarskoïe Selo",
    "Période Macédonienne Précédé par Constantin VIII Co-empereur Romain III Argyre (1028-1034",
    "Jean III de Navarre",
    "Pescennius Niger",
    "Louis le Pieux",
    "Isabelle de Valois",
    "Liste des ducs d'Auvergne",
    "Ballybricken",
    "Iunii",
    "Ofatinți",
    "Rue",
    "Fuente",
    "Clifton",
    "Québec)",
    "Valens",
    "Marlborough",
    "juin",
    "Liste des comtes de Saint-Pol",
    "Grand River",
    "Angelo Sanudo",
    "etit Palais (Avignon)",
    "Quintus Marcius Rex",
    "Othon IV de Bourgogne",
    "Hugues VI de Lusignan",
    "Mendorf,",
    "Idle",
    "Bibliographie",
    "Ecgberht",
    "Titres",
    "Ōhara",
    "Rue Demarquay",
    "Batanée",
    "Elizabethtown",
    "Knut le Grand",
    "2e",
    "Miniambaladougou",
    "Le",
    "Ordre cistercien",
    "Joinville",
    "Rue Jean-Pierre-Timbaud",
    "Mur",
    "Département de Constantine",
    "Gouvernement de Vologda",
    "Période Lascaris Précédé par Théodore I er Lascaris Suivi de Théodore II Lascaris Biographie Naissance vers 1192 Didymotique ( Empire byzantin",
    "p.",
    "Deacon's",
    "Empire d'Autriche",
    "Statuts de l'ordre de Saint-Michel",
    "Simon de Dammartin",
    "Los",
    "12e",
    "Empire romain",
    "Caldwell",
    "Montquin",
    "Arthur III de Bretagne",
    "Hobița",
    "Oulkhou",
    "Saint-Pierre-de-Caravenchel",
    "Felice Varini",
    "Shadwell",
    "Soudan anglo-égyptien",
    "Union",
    "Alain IV de Bretagne",
    "Marie de Bretagne",
    "Marguerite de Bar",
    "Kings",
    "Florent Ier de Frise occidentale",
    "Ordination",
    "Royaume de Macédoine",
    "Northumberland (comté)",
    "Charles II de Lorraine",
    "Duc des Francs",
    "Stinsford,",
    "Maison",
    "Saint-Henri",
    "Ach-Charqiya (Égypte)",
    "Rue Clément",
    "Charny",
    "Liste des comtes et ducs de Touraine",
    "Charles Ier de Bourbon",
    "Rue Louise-Émilie-de-La-Tour-d'Auvergne",
    "Guillaume VIII d'Aquitaine",
    "Suzanne de Bourbon",
    "Jeanne de Navarre",
    "Bad",
    "Maison de Choiseul",
    "Hugues Ier de Vermandois",
    "Lugal-zagesi",
    "Thibaud Ier de Blois",
    "de",
    "Podolie",
    "St.",
    "Plympton",
    "Hünshoven",
    "6ee341124611/Le Berceau de Dieu - Joseph (André Roanne) et Pharaon (Joë Hamman).jpg",
    "Réserve",
    "Arrondissement de Bergedorf",
    "14e",
    "Valerii",
    "Vitrail",
    "Maison de Sponheim",
    "Carignan",
    "Royaume d'Italie (Saint-Empire romain)",
    "Barretina",
    "Sophie",
    "Rue Monge",
    "Valdicastello,",
    "Lye",
    "Saint Pol Aurélien",
    "Califat omeyyade",
    "Adélaïde",
    "Depoy,",
    "Foulques Ier d'Anjou",
    "calendrier musulman",
    "Langage",
    "Durwood,",
    "Canada",
    "Plum",
    "Robert de Bruce",
    "Fenny",
    "Boulevard Saint-Martin (Paris)",
    "Diocèse d'Agen",
    "Liste des comtes d'Albon puis dauphins de Viennois",
    "Carin",
    "Liste des comtes et ducs de Valois",
    "Duché de Saxe",
    "Brady",
    "Mercie",
    "Commanderie",
    "Terre",
    "Liste des comtes et ducs de Chartres",
    "Danemark",
    "Andastan",
    "Faubourg",
    "Hugues V de Lusignan",
    "Années 1560",
    "Alcazar",
    "Liste des ducs et duchesses de Brabant",
    "South",
    "Jaloudok",
    "Fordstown",
    "Carpates",
    "Liste des souverains de Kiev#Grands-princes de Kiev",
    "Espagne wisigothique",
    "Jean-Louis de Savoie",
    "Holloway,",
    "Couronne de Castille",
    "Maison de Nevers",
    "Rue des Petits-Champs",
    "rue",
    "Mirza",
    "Liste des souverains de Brandebourg",
    "Famille Neville",
    "Denkhok",
    "West Kensington",
    "S:t",
    "Andronic Doukas",
    "Allegheny",
    "Great",
    "Gui de Dampierre",
    "Marguerite d'York",
    "Killaloe, Comté de Clare",
    "Liste des comtes de Soissons",
    "Ray",
    "Craon",
    "Liste des comtes de Rennes",
    "Comte",
    "Caecilii Metelli",
    "Tsarskoïe",
    "Maison de Dunkeld",
    "Terre sainte",
    "Gouvernement de Vladimir",
    "Philippe d'Alsace",
    "5e",
    "11e",
    "Louise de Savoie",
    "Westerham",
    "Alexandre",
    "Père",
    "Robert III de Flandre",
    "Kirkcudbrightshire",
    "Liste des dauphins d'Auvergne",
    "Royaume d'Italie (1861-1946)",
    "Hugues XII de Lusignan",
    "République de Weimar",
    "Vernon",
    "Duché d'Aquitaine",
    "Hamburg-Finkenwerder",
    "Norfolk",
    "desktopArticleTarget-targetContainer",
    "Nationalité Américaine Décès 2 juin 1981 (à 78 ans",
    "Palazzo",
    "Liste des conjoints des souverains de Naples",
    "Aurum",
    "Fullersburg",
    "Liste des comtes de Pardiac",
    "Croatie",
    "District",
    "Clovis Ier",
    "Herennius Etruscus",
    "Lieu",
    "Isabelle de Luxembourg",
    "Khamag Mongol",
    "Kayâ,",
    "Marguerite Aldobrandini",
    "Rue de Chaillot",
    "Rue du Faubourg-Saint-Honoré",
    "Assam",
    "Raj",
    "Province d'Afrique",
    "Raymond II de Tripoli",
    "Middelburg",
    "Eadwulf",
    ".",
    "Liste des comtes de Flandre",
    "Décès 28 juin 1385 (à 37 ans",
    "Maison de Barcelone",
    "Pape",
    "Liste des comtes puis ducs de Rethel",
    "Carlton",
    "Seconde maison de Bourbon-Montpensier",
    "Maurice V de Craon",
    "Paroisse de Saint James",
    "certain",
    "Odoacre",
    "Adams",
    "Julianus",
    "Wöhrd",
    "Liste des ducs de Schleswig",
    "Wiltshire",
    "Beeston",
    "Nouveau-Brunswick",
    "Rococo",
    "Abeadzi",
    "Rio",
    "Ville-Marie (ancien nom de Montréal)",
    "Marie de Juliers-Berg",
    "(~",
    "Raj britannique",
    "Paroisse de Sainte-Catherine",
    "Wolanka",
    "Wayne",
    "Sigismond",
    "Titus Quinctius Capitolinus Barbatus",
    "June Pointer",
    "Famille de Beaumont",
    "Catherine Woodville",
    "Calvinisme",
    "Vicomte",
    "Belgique",
    "Guatemala",
    "Pannonie",
    "Black Hills",
    "Cass",
    "Serguievka",
    "Empire russe",
    "Jean de Brienne",
    "Données clés Prédécesseur Isabelle le Despenser Successeur Élisabeth de Bohun Comtesse de Surrey 30 juin 1347 – 11 janvier",
    "Rottluff,",
    "Rue Sainte-Anne (Paris)",
    "Liste des comtes de Rodez",
    "Renfrew (Ontario)",
    "Maison d'York",
    "Aholičy",
    "Nottinghamshire",
    "Louis de Valois",
    "Algérie française",
    "Charles III de Bourbon",
    "Maison de la Cerda",
    "Bab",
    "Isabelle de Savoie",
    "Liste des monarques de France",
    "Maison de Wessex",
    "Cavalerie",
    "Perticara",
    "Valmont",
    "Albert Ier de Hainaut",
    "Herbert Ier de Vermandois",
    "Empire perse",
    "Derbyshire",
    "Ewodi",
    "Romagne",
    "Mayfield",
    "RSSA du Nakhitchevan",
    "Liste des comtesses de Flandre",
    "Užpaliai,",
    "Vieux",
    "voïvodie",
    "Comté de Hainaut",
    "Rue des Bourdonnais",
    "Deer",
    "Alix de Bretagne",
    "Château de Dillenbourg",
    "Smbat VIII Bagratouni",
    "Hale's",
    "Philippe d'Artois",
    "Glengormley",
    "Colonie du Cap",
    "Maroc",
    "Isaac",
    "Ozeriany",
    "Palace",
    "Alphonse Jourdain",
    "Vienne",
    "Santarcangelo",
    "–",
    "Fairfield,",
    "Schmiedefeld",
    "Maison de Habsbourg",
    "Bivinides",
    "Lucceius Albinus",
    "Charles V d'Anjou",
    "Newton",
    "Lucius Quinctius Cincinnatus",
    "Jeanne de Marle",
    "Ciudad",
    "Charles de Valois",
    "Bon-Secours",
    "Liste des comtes d'Armagnac",
    "Liste des comtes de Toulouse",
    "Grec ancien",
    "Valash",
    "Malye",
    "Place Charles-Dullin",
    "Ceolred",
    "Nassarao",
    "Monobaze Ier",
    "Raoul IV de Vexin",
    "Giarre-Riposto",
    "Kondol",
    "Constance Doukas",
    "Manor",
    "Liste des rois de Chypre",
    "Sri",
    "Chicora",
    "Tower Hill (Londres)",
    "Avitus",
    "Rue de Grenelle",
    "Hampstead",
    "Royaume de l'Aurès",
    "Coumanie",
    "Noms chinois",
    "Teutendorf",
    "Slezská",
    "Guillaume Ier de Craon",
    "Tour",
    "Dame de compagnie",
    "Ville libre d'Empire de Besançon",
    "Rebbelberga",
    "Philippe de Saint-Pol",
    "La Nuit du carrefour",
    "Toscane",
    "Maison de Chalon-Arlay",
    "Del",
    "Royaume de Cordoue",
    "Maison d'Anjou-Sicile",
    "Turquie",
    "Heyshott",
    "Enguerrand VII de Coucy",
    "Casimir Ier de Cujavie",
    "Arthur II de Bretagne",
    "Landgrave",
    "Lech le Blanc",
    "Paw",
    "château",
    "Liste des comtes de Champagne",
    "Mix",
    "Chypre (pays)",
    "Henri III de Brabant",
    "Östra",
    "Royaume de Castille",
    "Rue de Seine",
    "Sardaigne",
    "Duché de Châteauvillain",
    "Jean Ier de Namur",
    "Dynastie Han",
    "Catherine de France",
    "statue",
    "Rovine",
    "Charles II d'Albret",
    "Norfolk (comté)",
    "Louis Ier",
    "Syrie",
    "Kent",
    "Jean Ier de Choiseul",
    "Sainte-Rose (Laval)",
    "Yolande de Bourgogne",
    "Royaume de Navarre",
    "Sépulture",
    "Freidorf",
    "Jeanne Ire",
    "Conan IV de Bretagne",
    "Louis Ier de Chiny",
    "Empire",
    "Edenburg",
    "Magnus Ier de Saxe",
    "Constantin",
    "Stirlingshire",
    "Jean Ier de Craon",
    "Valentinien II",
    "Geoffroi Ier de Bretagne",
    "Louis-Alexandre",
    "Simon de Joinville",
    "Maison de Bourgogne au Portugal",
    "Province de Hamedan",
    "Green",
    "Henri II le Pieux",
    "Owain",
    "Pagus Bracbatensis",
    "Green's",
    "Liste des comtes de Hainaut",
    "Beorhtric",
    "Empire mongol",
    "von",
    "Frogmore",
    "Cheshire (comté)",
    "Fédération de <br",
    "Acton",
    "Période Macédonienne Précédé par Zoé Porphyrogénète Michel IV le Paphlagonien Co-empereur Zoé Porphyrogénète (1028-1050",
    "Conflits",
    "Henri Ier de Brandebourg",
    "Charles d'Artois",
    "Cullercoats",
    "Maison de Haro",
    "Knut d'York",
    "Liste des reines de Navarre",
    "Thomas Montagu",
    "Pascweten",
    "Liste des comtes de Namur",
    "Royaume d'Aragon",
    "Robert II de Dreux",
    "Szetejnie",
    "Maison d'Albret",
    "Barnesboro",
    "Julie Taymor",
    "Origine",
    "Bourgogne",
    "Lucius Furius Medullinus",
    "Pologne",
    "Henri Ier de Vianden",
    "Provinces-Unies",
    "Hannah",
    "Nevill",
    "Jeanne de Ponthieu",
    "Athaulf",
    "Taras",
    "Marino",
    "Neufchâteau",
    "est",
    "Alexis Ier Comnène",
    "Virginio Orsini",
    "Seigneur",
    "Sancha de Castille",
    "Fenenna de Cujavie",
    "Currie,",
    "Castledawson",
    "Rocky",
    "Henri Ier de Brabant",
    "Liste des ducs de Nemours",
    "Sibodal",
    "Essex",
    "Maire du palais",
    "Toxteth",
    "Héricourt",
    "Piémont",
    ";",
    "Jaunpils",
    "Jean Arthur",
    "Ferry IV de Lorraine",
    "Penza Nationalité Empire russe Décès 2 février 1940 (à 65 ans",
    "Jean Ier de Chalon",
    "Liste des souverains de Provence",
    "Boson de Provence",
    "Thessalie",
    "Latin",
    "Kirkwood",
    "Guillaume V de Juliers",
    "hypothèse",
    "Kona Nord",
    "Maredudd ap Gruffydd",
    "Jomei",
    "Charles",
    "Saad al-Dawla",
    "Henri Ier",
    "Maison de Bourbon-La Marche",
    "Raoul II de Brienne",
    "Yolande d'Aragon",
    "Guy de Luxembourg-Ligny",
    "Vienne",
    "Coldirodi",
    "Guillaume Ier de Hainaut",
    "Guerre de Cent Ans",
    "Louise",
    "Lewisham",
    "Rollonides",
    "Daniel Mesguich",
    "Coffeen",
    "Hawarden",
    "Podgórze (Cracovie)",
    "Charles IV du Maine",
    "Richard Ier de Normandie",
    "Dobbs",
    "Dompierre",
    "Seigneurie d'Ibelin",
    "Pont-l'Évêque",
    "Saint-Omer",
    "Hunan",
    "Bertrade de Montfort",
    "Jean-Guillaume de Clèves",
    "Guillaume Ier de Bourgogne",
    "Temple",
    "Daniel de Galicie",
    "Taraise de Constantinople",
    "Hallebardier",
    "Comté de Brunswick (Basse-Saxe)",
    "Londres,",
    "Données clés Prédécesseur Création du titre Successeur Confiscation du titre Fonctions militaires Commandement Lord lieutenant d'Irlande Faits d’armes Bataille de Bosworth Bataille de Stoke Conflits Guerre des Deux-Roses Biographie Dynastie Famille de la Pole Distinctions Ordre du Bain Naissance 1462 ou 1464 Décès 16 juin",
    "Belmonte",
    "Mathilde de Brabant",
    "Liste des comtes de Ligny",
    "Väversunda",
    "Ville libre de Cracovie",
    "Wuxing",
    "Iaroslavl Décès 1 er mars 1936 (à 63 ans",
    "Charles Ier d'Anjou",
    "Shannonbridge",
    "Royaume de Géorgie",
    "Voisenon",
    "Bosonides",
    "Alain d'Albret",
    "New York%2C N.Y.%2C ca. Aug. 1947) (LOC) (4843140781).jpg",
    "Warwickshire",
    "Sheen",
    "Schöneberg",
    "Constance de Portugal",
    "Gaule romaine",
    "lagune et au sud la baie de Carthagène",
    "Rue de la Verrerie (Paris)",
    "Al-Jamāliyah",
    "Tyrone",
    "Royaume de Portugal",
    "Élisabeth de Clèves (1378-1430)",
    "São",
    "Paul de Constantinople",
    "Glenlohan",
    "Grenade (pays)",
    "Raymond V de Toulouse",
    "anecdote",
    "Gravelly",
    "Bernicie",
    "Herman de Hainaut",
    "Mathilde de Carinthie",
    "Geoffroy Ier de Lusignan (seigneur de Vouvant)",
    "Chatham",
    "Marian-glas",
    "ourceLoaderDynamicStyles",
    "Mongolie",
    "Nutahigashi,",
    "Aquitaine",
    "Ivarr de Waterford",
    "Tchijovo",
    "Liste des comtesses de Hollande",
    "Guy XII de Laval",
    "Robert Ier de Flandre",
    "Anne",
    "Liste des monarques de Danemark",
    "photographe",
    "Sinuessa",
    "Portugal",
    "Abdon",
    "Afrique du Sud",
    "Gilbert de Montpensier",
    "Empire romain d'Occident",
    "Ouïezd",
    "Ivy",
    "Le facteur sonne toujours deux fois (film, 1946)",
    "Antigonides",
    "Liste des comtes puis ducs de Montpensier",
    "Famille de Bueil",
    "Charlesbourg",
    "Pierre Ier",
    "Clytemnestre",
    "Thibaut VI de Blois",
    "Maximin Ier le Thrace",
    "Sophie de Rheineck",
    "Garden",
    "Kirkharle",
    "Liste des seigneurs de Ravensberg",
    "Usurpateur romain",
    "Marie Stuart",
    "Raoul Ier de Soissons",
    "Elpidius",
    "Sant Gervasi de Cassoles",
    "Califat abbasside",
    "Berkswell",
    "Chypre",
    "Comté d'Édesse",
    "Duché de Bavière-Ingolstadt",
    "Époque",
    "Tabarestan",
    "Jean II de Bourgogne",
    "Galba",
    "Tinta,",
    "Seigneurie de Naplouse",
    "Eloxochitlán",
    "Isabelle de Brienne",
    "Concession française de Shanghai",
    "Juan",
    "Journal",
    "Nolde",
    "Waccho",
    "Guy XVI de Laval",
    ". (la",
    "Saint-Louis",
    "Collégiale Saint Georges",
    "Center",
    "Royaume d'Est-Anglie",
    "Lorette",
    "Bowden",
    "Jean de Bourgogne",
    "Capitaine",
    "Lancashire",
    "Abbaye Sainte-Madeleine de Geneston",
    "Traduction",
    "Lužki",
    "Kunzendorf,",
    "lieu",
    "fils,",
    "Louis II de Chalon-Arlay",
    "Géjé",
    "Constance de France",
    "Paul II",
    "Conan Ier de Bretagne",
    "Asie centrale",
    "Isabelle de Meulan",
    "Liste des comtes de Barcelone",
    "Geoffroy Ier de Marseille",
    "Philippe II de Bourgogne",
    "Saint",
    "États-Unis",
    "Henri III de Louvain",
    "Louis-Philippe Ier",
    "Claude Catherine de Clermont",
    "Casimir II le Juste",
    "Comminges",
    "Jeanne d'Armagnac",
    "1er",
    "Flandre",
    "Bohême",
    "Royaume des Massyles",
    "Gerberge de Provence",
    "Agdjibedi,",
    "Hollingworth",
    "Famille Sanudo",
    "palmarès",
    "taille (anthropométrie)",
    "nom",
    "française",
    "taille",
    "alive",
    "taille 1",
    "(consulté",
    "québec",
    "canadienne",
    "américaine",
    "doctorat",
    "nationalités",
    "formation",
    "club",
    "press",
    "parlement d'angleterre",
    "royaume-uni de grande-bretagne et d'irlande",
    "arts visuels",
    "arabe",
    "natation sportive",
    "préfecture",
    "ontario",
    "britannique",
    "empire ottoman",
    "hong",
    "il",
    "elle",
    "hong kong (colonie)",
    "corée du sud",
    "parcours",
    "prpoids de formeess",
    "surrey (comté)",
    "pseudonyme",
    "or",
    "militantisme",
    "les",
    "catégorie",
    "histoire de l'art",
    "surnom",
    ":",
    "yorkshire",
    "essaie",
    "carrière",



    "tibet",
    "ohio",
    "nouvelle",
    "texas",
    "anthropologie",
    "disc jockey",
    "linguistique",
    "irlande",
    "st",
    "corée",
    "floride",
    "afrique du sud",
    "grec moderne",
    "records",
    "massachusetts",
    "michigan",
    "illinois",
    "las",
    "belge",
    "roman policier",
    "période",
    "exploration",
    "art contemporain",
    "gravure",
    "mannequinat",
    "john",
    "louis",
    "hertfordshire",
    "tel",
    "villa",
    "saison",
    "hull (québec)",
    "massachusetts institute of technology",
    "football",
    "port",
    "kingston",
    "xian",
    "langues chinoises",
    "jonquière",
    "française",
    "professeur",
    "russe",
    "pierre",
    "north",
    "françois",
    "tripoli",
    "wisconsin",
    "connecticut",
    "côte d'ivoire",
    "république",
    "caractéristiques",
    "suisse",
    "province",
    "jazz",
    "nouvelle-galles du sud",
    "royaume d'angleterre",
    "east",
    "bachelor of arts",
    "laval",
    "entraîneur",
    "tchécoslovaquie",
    "jeux olympiques antiques",
    "guitare",
    "liste de peintres italiens",
    "minnesota",
    "consul",
    "allemande",
    "royaume d'italie",
    "indiana",
    "anglais",
    "bachelor of science",
    "william",
    "sussex",
    "beaux-arts de paris",
    "7e",
    "japonaise",
    "sicile",
    "iowa",
    "trinity college",
    "lincolnshire",
    "devon (comté)",
    "animateur",
    "astronomie amateur",
    "kham",
    "autres",
    "mount",
    "louisiane",
    "piano",
    "situation",
    "rallye automobile",
    "république démocratique du congo",
    "saskatchewan",
    "chef tribal",
    "chevalier",
    "musique classique",
    "libanaise",
    "suffolk",
    "royaume",
    "rap",
    "reggae",
    "jiangsu",
    "calligraphie",
    "oxfordshire",
    "nationalité",
    "décès",
    "activité",
    "ancien",
    "new",
    "alive",
    "enseignement",
    "poste",
    "san",
    "paroisse",
    "rome antique",
    "los",
    "biographie",
    "saint",
    "royaume de france",
    "californie",
    "genre",
    "activités",
    "traduction",
    "grec ancien",
    "empire russe",
    "comté",
    "new jersey",
    "são",
    "empire romain",
    "buenos",
    "haut-empire romain",
    "district",
    "chicoutimi",
    "croydon",
    "père",
    "rio"

]

BAD_WIKI_PAGE = [
    "Art and Language",
    "Saïan Supa Crew",
    "G-Unit",
    "D-Block Europe",
    "Vitor Hublot",
    "5.5 designers",
    "Le Klub des 7",
    "Chocolate Genius Inc.",
    "83 (collectif)",
    "Spoke Orkestra",
    "Maison d'édition",
    "Histoire de la médecine dentaire",
    "Histoire de ma vie (Casanova)",
    "Histoire de vie",
    "Histoire des fonctions trigonométriques",
    "L'Histoire est une littérature contemporaine",
    "L'Incroyable Histoire du facteur Cheval",
    "Société africaine de plantations d'hévéas",
    "Société d'accélération du transfert de technologies",
    "Société d'études de l'histoire régionale du pays de l'Ems",
    "Société patriotique du Luxembourg",
    "Prix Alfred-Kordelin",
    "Prix Costa",
    "Prix Watson Davis et Helen Miles Davis",
    "Prix d'histoire André-Castelot",
    "Benedetta (film)",
    "Dangal (film),"
    "Frida (film)",
    "William Stage Boyd",
    "Wardell Poochie Fouse",
    "Al TNT Braggs",
    "Benjamin Pap Singleton",
    "Carlton Santa Davis",
    "Demetrius Hook Mitchell",
    "Edmund Trotsky Davies",
    "Floyd Candy Johnson",
    "Frances Franco Stevens",
    "Freddie Fingers Lee",
    "Gene Bowlegs Miller",
    "Greg Cadillac Anderson",
    "Jacques-Antoine Cassiodore Demonchaux",
    "Jacques Kako Bessot",
    "John Charlie Whitney",
    "Johnny Man Young",
    "Leon Ndugu Chancler",
    "Mohibullah Mo Khan",
    "Peter Cool Man Steiner",
    "Richard Humpty Vission",
    "Royce da 5'9",
    "Sergio Pipian Martinez",
    "Sidney Big Sid Catlett",
    "Thomas Tom Flanagan",
    "Maison d'Este",
    "Maison de Fürstenberg",
    "Maison de Gonzague",
    "Maison de Hohenlohe",
    "Maison de Joyeuse",
    "Maison de Montefeltro",
    "Maison de Nicéphore Niépce",
    "Maison de Salm",
    "Maison de Trazegnies",
    "Maison de Wavrin",
    "Maison de Zähringen",
    "Maison de la poésie de Montréal",
    "Maison de naissance d'Isaac Newton",
    "Maison de naissance de Tchaïkovski",

]


TOWN_TO_LOCALISATION_DICT = {
    "berlin":"52° 31′ N, 13° 23′ E",
    "bruxelles":"50° 51′ 01″ N, 4° 21′ 00″ E",
    "hambourg":"53° 33′ N, 10° 00′ E",
    "königsberg":"54° 44′ N, 20° 29′ E",
    "edo (ville)":"35° 41′ 22″ N, 139° 41′ 30″ E",
    "Chicoutimi":"48° 25′ 00″ N, 71° 04′ 00″ W",
    "santa":"43° 09′ 57.30″ N, 4° 02′ 49.41″ W",
    "berlin-est":"52° 31′ N, 13° 23′ E",
    "berlin-ouest":"52° 31′ N, 13° 23′ E",
    "berlin est":"52° 31′ N, 13° 23′ E",
    "berlin ouest":"52° 31′ N, 13° 23′ E",
    "valence":"39° 28′ 13″ N, 0° 22′ 36″ W",
    "washington":"38° 53′ 42″ N, 77° 02′ 12″ W",
    "vienne":"48° 12′ 30″ N, 16° 22′ 21″ E",
    "saint-denis":"48° 56′ 08″ N, 2° 21′ 14″ E",
    "surabaya":"7°15′40.71″S 112°44′59.13″E"
}